### ISSUE TITLE
Idea: complete AbstractAssert.as...() methods

### ISSUE THREAD

**Issue by tkruse** [assertj/assertj#1020]
Hi,
just an idea, similar to AbstractAssert.asList(), AbstractAssert could have asOptional, asMap, ... returning the respective specialized Assertions instance.

I think this is particularly useful in combination with .extracting()

**Comment by tkruse** [comment]
Also, I wonder if asList() could be extended to take a class as argument like:
```
assertThat(listAsObject).asList(Integer.class).allMatch(v -> v > 10);
```

**Comment by joel-costigliola** [comment]
That we can do.

**Comment by jonfreedman** [comment]
How about changing the `isInstanceOf` & `isExactlyInstanceOf` signatures to cast?

**Comment by oliverlockwood** [comment]
Plus one to `asMap()`.

**Comment by joel-costigliola** [comment]
I believe you have been heard ;-) https://github.com/joel-costigliola/assertj-core/pull/1498

**Comment by scordio** [comment]
Hi @tkruse, could you check if [`asInstanceOf`](https://assertj.github.io/doc/#assertj-core-3.13.0-asInstanceOf) satisfies your requirements?

**Comment by tkruse** [comment]
yes, seems this can be closed.
