### ISSUE TITLE
Consider accessing XML String assertions with assertThatXml

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj#119]
This will separate String assertion from XML assertion to avoid polluting String assertions.

If we go this way, we should deprecate isXmlEqualTo assertion that is changing  

``` java
assertThat(oneLineXml).isXmlEqualTo(expectedXml);
```

to

``` java
assertThatXml(oneLineXml).isEqualTo(expectedXml);
```

It would be cleaner when we add other XML assertion like `hasElement` for example.

``` java
assertThatXml(xmlString).hasElement("<price>");
```

**Comment by wlokes** [comment]
Hello! Was this feature ever implemented: `assertThat(xml).asXml().hasXPathNode(xpath);`?

**Comment by joel-costigliola** [comment]
No we think that a proper XML assertions library is the way to go, not that I don't want to see it in AssertJ, it is just too much work. 
I would suggest using http://www.xmlunit.org/
