### ISSUE TITLE
Feature request: mechanism to raise exception on malformed assertions

### ISSUE THREAD

**Issue by JensPiegsa** [assertj/assertj#1340]
#### Summary

I wonder if there is a way to implement a clever mechanism that makes malformed assertions raise an exception. Juniors sometimes struggle with the syntax. I think that would lower the entry barrier for beginners.

#### Example

```java
List<String> list = Arrays.asList("Alice", "Bob");
assertThat(list.contains("Alice")); // incorrect (malformed - no assertion happens here)
assertThat(list).contains("Alice"); // correct
```

**Comment by PascalSchumacher** [comment]
Static code inspection tools like ErrorProne, SpotBugs and Findbugs can detect these kind of error.

See discussion in https://github.com/joel-costigliola/assertj-core/issues/979 for details.

**Comment by joel-costigliola** [comment]
As @PascalSchumacher said it's a job static code analysis for.
There's not much more AssertJ can do about it unfortunately, using SpotBugs addresses your example BTW.

**Comment by JensPiegsa** [comment]
We installed SpotBugs for Eclipse and got orange bugs. :-)
Thank you both @joel-costigliola and @PascalSchumacher.
