### ISSUE TITLE
Introduce Maven BOM for AssertJ artifacts

### ISSUE THREAD

**Issue by mp911de** [assertj/assertj#1437]
#### Summary
To ease consumption of _AssertJ_ artifacts, it would be great to introduce a Maven _Bill Of Materials_ POM ([search for BOM here](https://maven.apache.org/guides/introduction/introduction-to-dependency-mechanism.html)) for all AssertJ artifacts that are released as part of an AssertJ release (`assertj-core`, `assertj-swing`, `assertj-guava`, …).

A BOM simplifies consumption of artifacts that wish to use one or more AssertJ dependencies. It bundles compatible artifact versions. BOM usage no longer requires dependency descriptors to declare versions for individual artifacts, only a single version identifier is required to import the BOM.

See the [netty-bom](https://github.com/netty/netty/blob/4.1/bom/pom.xml) project from Netty for inspiration.

**Comment by joel-costigliola** [comment]
I have created a new project for the assertj bom and moved this issue there https://github.com/assertj/bom/issues/1.
Might be a bit overkill for just one pom.xml ... but I haven't thought of a better option at the moment.

**Comment by scordio** [comment]
Reopening as we'll add a BOM as a consequence of #2424.
