### ISSUE TITLE
Java 11 illegal reflective access operation using soft assertions

### ISSUE THREAD

**Issue by scaphoid** [assertj/assertj#1554]
#### Summary

I saw the earlier "resolved" issues with reflection in Java 9 and up, but this seems even more fundamental?

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.assertj.core.api.AbstractSoftAssertions ... to field java.lang.Throwable.detailMessage
```

#### Example

```java
SoftAssertions softly = new SoftAssertions();
softly.assertThat("x").isEqualTo("y");
softly.assertAll();
```

**Comment by PascalSchumacher** [comment]
Thanks for reporting.

I am closing this issue because it was already reported, see: https://github.com/joel-costigliola/assertj-core/issues/1165#issuecomment-367473974
