### ISSUE TITLE
Provide a way to the get the current actual

### ISSUE THREAD

**Issue by rupert-madden-abbott** [assertj/assertj#1931]
#### Summary

Some assertions have side effects or traverse the objects under test.

Sometimes, it is desirable to assert something, then perform additional manipulations on the object under test, before asserting more things.

In these cases, you have 2 choices:

1. Perform the traversal outside of assertj and then assert as you reach the relevant pieces.
2. Duplicate the traversal both with and without assertj

It would be useful instead if all assertions allowed for the actual object to be retrieved, removing this duplication.

Please let me know if there is already a way to do this (or a better approach) but I can't see one.

Below examples show this with succeedsWithin but the problem is not specific to succeedsWithin.

### Inconvenient Alternative 1

```java
  //no way to access what the future returned
  assertThat(future).succeedsWithin(10, TimeUnit.SECONDS);

  //Duplicate the traversal logic
  Object foo = future.get();

  //manipulate object outside of assertj
  //perform further assertions
```

### Inconvenient Alternative 2

```java
  //Get the underlying object first. Don't use assertj and lose the assertion failures if something goes wrong
  Object foo = future.get()  
  
  //manipulate object outside of assertj
  //perform further assertions
```

### Desired Outcome
```java
  Object foo = assertThat(future)
    .succeedsWithin(10, TimeUnit.SECONDS)
    .getActual();

  //manipulate object outside of assertj
  //perform further assertions
```

### Proposed Solution

Just add a getter to AbstractAssert:

```java
  public ACTUAL getActual() {
    return actual;
  }
```

**Comment by joel-costigliola** [comment]
The team is not convinced exposing `getActual` is worth it at the moment, we believe option 1 is acceptable.

For future what we could do is something similar to optional and add [`get()`](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.1/org/assertj/core/api/AbstractOptionalAssert.html#get())/[`get(InstanceOfAssertFactory)`](https://www.javadoc.io/static/org.assertj/assertj-core/3.18.1/org/assertj/core/api/AbstractOptionalAssert.html#get(org.assertj.core.api.InstanceOfAssertFactory)) to the API to be able to assert on the future's result.
```java
assertThat(futureString).succeedsWithin(10, TimeUnit.SECONDS)
                        .get(InstanceOfAssertFactories.STRING)
                        .startsWith("foo");
```

**Comment by mgrafl** [comment]
It's a pity that this proposal was rejected. I was also looking forward to such a feature. 

I sometimes have integration tests that check a certain workflow. It would be very handy to verify the structured response from one operation down to a nested field and then use that value for another operation (without having to repeat the extraction). 
For example: 
```java
List<CustomerDiagnostic> customerDiagnostics = diagnosticService.getCustomerDiagnostics(todaysTimeRange);

// Online shop had one customer today (Joe), who had three different shopping sessions, the last one being still active
String sessionId = assertThat(customerDiagnostics).singleElement()
                                                  .returns("Joe", from(CustomerDiagnostic::getName))
                                                  .extracting(CustomerDiagnostic::getSessionHistory, 
                                                              as(list(ShoppingSession.class)))
                                                  .hasSize(3)
                                                  .last()
                                                  .extracting(ShoppingSession::getSessionId, as(STRING))
                                                  .hasSize(32)
                                                  .getActual();

boolean isSessionActive = sessionService.isSessionActive(sessionId);
assertThat(isSessionActive).isTrue();

sessionService.doSomethingWithSession(sessionId);
```

**Comment by joel-costigliola** [comment]
@mgrafl the assertion `assertThat(isSessionActive).isTrue();` can be done after `.hasSize(32)` with a call to `satisfies`.

**Comment by joel-costigliola** [comment]
The team has discussed again and we still think adding `getActual` is not worth it.

**Comment by mgrafl** [comment]
Okay. Thanks for the reconsideration though.

**Comment by rupert-madden-abbott** [comment]
In case it helps, this is how I workaround this issue when I need to a) assert that a Future completes within a certain time and b) get the result of that Future so that I can use it for subsequent, non-assertion calls i.e. an integration test.

```java
    public static <T> T assertSucceedsWithin(Future<T> future, long timeout, TimeUnit timeUnit) {
        try {
            return future.get(timeout, timeUnit);
        } catch (InterruptedException | ExecutionException | TimeoutException | CancellationException e) {
            String message = "%n"
                    + "Expecting%n"
                    + "  <%s>%n"
                    + "to be completed within %s %s.%n%n"
                    + "exception caught while trying to get the future result: ";
            fail(String.format(message, future, timeout, timeUnit), e);
            //This will never be thrown because fail throws but the compiler isn't clever enough to work that out.
            throw new RuntimeException(e);
        }
    }
```

**Comment by mgrafl** [comment]
It is clear that `getActual()` will not become part of the AssertJ API and I don't want to reheat the discussion. 
Anyway, if anyone is looking for a custom extension, consider this snippet: 
```java
public class ActualReturningAssert<ACTUAL> extends AbstractAssert<ActualReturningAssert<ACTUAL>, ACTUAL> {

	protected ActualReturningAssert(ACTUAL actual) {
		super(actual, ActualReturningAssert.class);
	}
	
	public ACTUAL getActual() {
		return actual;
	}
	
	/**
	 * Allows returning the <em>actual</em> element of an Assertion.
	 * 
	 * <p>Example:
	 * <pre>String singleEntry = Assertions.assertThat(myStringList)
	 *   .singleElement(as(actualReturning(String.class)))
	 *   .getActual();</pre>
	 *
	 * @param <ACTUAL>  type of the actual element
	 * @param actualClass  class of the actual element
	 * @return AssertFactory decorator for use in <code>asInstanceOf(...)</code> 
	 *     that provides access to the actual element
	 */
	public static <ACTUAL> InstanceOfAssertFactory<ACTUAL, ActualReturningAssert<ACTUAL>> 
        actualReturning(Class<ACTUAL> actualClass) {
		return new InstanceOfAssertFactory<>(actualClass, ActualReturningAssert::new);
	}
}
```
