### ISSUE TITLE
add method "ACTUAL andReturn(){ return actual; }"

### ISSUE THREAD

**Issue by ScheintodX** [assertj/assertj#2098]
#### Summary
While writing assertions it is pretty useful being able to access the object tested.
All my own Assertions classes have this method.

#### Example

```java
Hobbit froodo = assertThat( new Hobbit( "Froodo" ) )
    .hasName( "Froodo" )
    .isHungry()
    .andReturn();
assertThat( froodo.eat() )
    .isNotHungry();
```

**Comment by scordio** [comment]
The topic was recently discussed in #1931 and the team is not convinced about exposing `actual` with a dedicated API, as on average there are ways to achieve the same without it.

Even the example here can be solved without `andReturn()`:

```java
Hobbit froodo = new Hobbit( "Froodo" );
assertThat( froodo )
    .hasName( "Froodo" )
    .isHungry();
assertThat( froodo.eat() )
    .isNotHungry();
```

I'm closing the issue for now but I'm happy to reopen it if there are more concrete cases to evaluate.
