### ISSUE TITLE
Refactoring: introduce IntrospectionStrategy in the recursive comparison

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj#2189]
#### Summary

The recursive comparison would benefit from a clear introspection strategy when gathering the field to compare and getting their values.

The recursive comparison is a bit inconsistent, it introspects fields to get the list of fields to compare but uses a different strategy to read their values by looking first to a getter then reading the field directly or looking for a map value (key being the field name).

The IntrospectionStrategy would define what to compare and how to read the values to compare.

This is needed for: 
* https://github.com/assertj/assertj-core/issues/2108 
* https://github.com/assertj/assertj-core/issues/2149

edit: other related issues
* https://github.com/assertj/assertj-core/issues/2554
* https://github.com/assertj/assertj/issues/2314

**Comment by scordio** [comment]
@nach-o-man could you please comment here so I can assign the issue to you?

**Comment by nach-o-man** [comment]
Comment
