### ISSUE TITLE
Extracting from List of Maps throws exception

### ISSUE THREAD

**Issue by filiphr** [assertj/assertj#2419]
#### Example

```java
List<Map<String, Object>> elements = new ArrayList<>();
Map<String, Object> map = new HashMap<>();
map.put("name", "Yoda");
elements.add(map);
map = new HashMap<>();
map.put("name", "Luke");

```

**Comment by scordio** [comment]
Hi @filiphr, I guess this one was sent by mistake and #2420 is the proper one, right?

**Comment by scordio** [comment]
Closing, but let us know if there is anything else we should consider.

**Comment by filiphr** [comment]
I don't know how I ended up with 2. I guess I clicked a button while writing the first one and didn't realize. Sorry for the noise. Yes the other one is the right one. Thanks for closing this one
