### ISSUE TITLE
Additional assertions for `CharSequence`

### ISSUE THREAD

**Issue by scordio** [assertj/assertj#2472]
Using the existing `matches(Pattern)` and POSIX regex character classes, we can add specialized assertions to `AbstractCharSequenceAssert`.

```java
assertThat(string).isAlphabetic();   // \p{Alpha}
assertThat(string).isAlphanumeric(); // \p{Alnum}
assertThat(string).isASCII();        // \p{ASCII}
assertThat(string).isDigit();        // \p{Digit}
assertThat(string).isHexadecimal();  // \p{XDigit}
assertThat(string).isPrintable();    // \p{Print}
assertThat(string).isVisible();      // \p{Graph}
```

Also, the existing `containsOnlyDigits()` should be deprecated in favor of `isDigit()`.

**Comment by NeshkaD** [comment]
Hi, can you assign this to me, please?

**Comment by scordio** [comment]
Sure and thank you, @NeshkaD.

**Comment by chagmed** [comment]
Very good suggestions. Thank you, @scordio.

`isNumeric()` implies _this is a string representation of a number — ANY number_
`containsOnlyDigits()` says _this string contains ONLY digits_

The names `containsOnlyDigits()` and `isDigit()` are consistent with the POSIX character class `\p{Digit} — A decimal digit: [0-9]`. The character class is _not_ named `\p{Numeric}`. Naming consistency is useful to both API maintainers and consumers.

Assertions should be named to adhere to the _Principle of Least Surprise_ — they should behave as most API consumers would expect them to. E.g., the presence of a distinct `isHexadecimal()` assertion informs me that `\p{Digit}` will not match all valid numeric string representations, hexadecimal strings among them.

I would expect an `isNumeric()` assertion to succeed with the `float` string `"12.03456789"`

```java
String floatStr = "12.03456789";
assertThat(floatStr).isNumeric();
```

Given that the example `float` (and many other valid numeric String representations) do not match `\p{Digit}`, it would be clearer to indicate that the assertion succeeds _only_ if the string contains solely digits, i.e., `isDigit()`.

**Comment by scordio** [comment]
Honestly speaking, I've taken inspiration from [RandomStringUtils](https://commons.apache.org/proper/commons-lang/apidocs/org/apache/commons/lang3/RandomStringUtils.html), but I see the point about `isNumeric`.

I agree `isDigit` is a more sensible name, thanks for that @chagmed.

@NeshkaD would you mind taking this into consideration?

**Comment by scordio** [comment]
**Team decision**

The following assertions will be included:

```java
assertThat(string).isAlphabetic();   // \p{Alpha}
assertThat(string).isAlphanumeric(); // \p{Alnum}
assertThat(string).isASCII();        // \p{ASCII}
assertThat(string).isHexadecimal();  // \p{XDigit}
assertThat(string).isPrintable();    // \p{Print}
assertThat(string).isVisible();      // \p{Graph}
```

The existing `containsOnlyDigits` will not be deprecated.

**Comment by joel-costigliola** [comment]
@NeshkaD thanks! We have integrated your PR.
