### ISSUE TITLE
Add (Abstract)StringAssert#as(Boolean|Byte|Short|Integer|Long|Float|Double)

### ISSUE THREAD

**Issue by onacit** [assertj/assertj#2520]
#### Summary

This is a refined feature request derived from #2509.
Per @scordio's [commented](https://github.com/assertj/assertj-core/issues/2509#issuecomment-1057395093), it might be reasonable to add following signatures.

```java
AbstractStringAssert#asBoolean() returns BooleanAssert

AbstractStringAssert#asByte() returns ByteAssert
AbstractStringAssert#asByte(int radix) returns ByteAssert

AbstractStringAssert#asShort() returns ShortAssert
AbstractStringAssert#asShort(int radix) returns ShortAssert

AbstractStringAssert#asInteger() returns IntegerAssert
AbstractStringAssert#asInteger(int radix) returns IntegerAssert

AbstractStringAssert#asLong() returns LongAssert
AbstractStringAssert#asLong(int radix) returns LongAssert

AbstractStringAssert#asFloat() returns FloatAssert

AbstractStringAssert#asDouble() returns DoubleAssert
```

`NumberFormatException` throwable from those `parse...(String)` methods, except the [`Boolean#parseBoolean`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Boolean.html#parseBoolean(java.lang.String)), should be regarded as failing assertions.

#### Example

```java
assertThat("yes")
//        .isNotNull() // implicit
        .asBoolean()
        .isTrue(); // fails
assertThat("32")
        .asInteger()
        .isEqualTo(32); // succeeds
assertThat(".0d")
        .asDouble()
        .isZero();
```

**Comment by onacit** [comment]
A side concern arose regarding the naming.

I just hit by `parse` methods defined in classes reside in `java.time` package.

```java
TemporalAccessor expected;
assertThat("2022-03")
        .asYearMonth()
        .hasSameField(actual, ChornoField.YEAR);
```

the `asYearMonth()` method seems have no problem but `parsesIntoYearMonth` may look better.

```java
TemporalAccessor actual;
assertThat("2022-03")
        .parsesIntoYearMonth(DateTimeFormatter.XXX)
        .hasSameYear(actual, ChornoField.YEAR);
```

**Comment by HeZean** [comment]
Hi, I am interested in this. If these modifications are considered necessary, can you assign me?

**Comment by joel-costigliola** [comment]
We are agreeing to this as it is limited to string assertions

**Comment by joel-costigliola** [comment]
Addressed by https://github.com/assertj/assertj/pull/2580
