### ISSUE TITLE
Spotless check for formatting preferences

### ISSUE THREAD

**Issue by hjir** [assertj/assertj#2530]
#### Summary

I noticed that in your `CONTRIBUTING.md` file, you mention to use Eclipse formatting preferences and there is an Eclipse Formatter file with all the rules defined. However, the style of the code is not actually checked with the Continuous Integration workflows. 

Since the Eclipse Formatter file with all the rules already exists, it should be pretty straightforward to use [spotless](https://github.com/diffplug/spotless/blob/main/plugin-maven/README.md) - this could then be used as a maven command by users and it could be easily integrated as another workflow to check PRs. 

Let me know if this is something that you'd want for the project, I would love to pick it up :)

**Comment by scordio** [comment]
Yes, that would be nice! Thanks for picking this up, @hjir.

**Comment by scordio** [comment]
This was finally merged. Thanks, @hjir!
