### ISSUE TITLE
Cumbersome usage of has(Condition) with exceptions

### ISSUE THREAD

**Issue by szpak** [assertj/assertj#259]
When Assertj is used with [fluent-exception-rule](https://github.com/wjtk/fluent-exception-rule/) it is useful to have an ability to define a condition to evaluate an exception field value. E.g.

```
    thrown.expect(WithFieldException.class).has(new Condition<WithFieldException>() {
        @Override
        public boolean matches(WithFieldException value) {
            return value.getFieldValue() == 4;
        }
    });
```

Unfortunately `has` in `ExtensionPoints` is defined as `S has(Condition<? super A> condition)` which causes Throwable to be used and forcing casting down to a specific exception in `matches` implementation.

```
    thrown.expect(WithFieldException.class).has(new Condition<Throwable>() {
        @Override
        public boolean matches(Throwable value) {
            return ((WithFieldException)value).getFieldValue() == 4;
        }
    });
```

In that case `S has(Condition<? extends A> condition)` would be better, but playing with the code I am not sure if it can be easily achieved.

**Comment by szpak** [comment]
The same problem is also in Java 8 version:
`AbstractAssert.matches(Predicate<? super A> predicate, String predicateDescription)`.

**Comment by joel-costigliola** [comment]
The signature takes a lower bounded wildcard `? super A` to get flexibility of passing a `Condition` of `A` or one of its supertype, that is one can pass `Condition<Object>`.
This is useful so this is something I would like to keep.

**Comment by szpak** [comment]
I see the point.

Probably it will not be very easy to implement (and I'm not sure is it worth to spend time on it), but maybe as an enhancement there could be a new more narrow typed *Assert class instance created after `isInstanceOf` (or similar) to allow to use Condition/Predicate `<? super MoreNarrowException>` in consecutive methods?

**Comment by joel-costigliola** [comment]
Closing as won't fix as the benefits don't clearly outweigh the breaking change.
