### ISSUE TITLE
`InputStream` supporting `mark` / `reset` should not be manipulated by assertions

### ISSUE THREAD

**Issue by scordio** [assertj/assertj#2596]
Related to https://github.com/assertj/assertj-core/issues/2490#issuecomment-1035488261, the assertions of `AbstractInputStreamAssert` could avoid manipulating the stream position when the `InputStream` implementation supports [`mark`](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#mark-int-) / [`reset`](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#reset--) operations, tested by [`markSupported`](https://docs.oracle.com/javase/8/docs/api/java/io/InputStream.html#markSupported--).

**Comment by nith2001** [comment]
Can @jessicant and myself take this issue?

**Comment by scordio** [comment]
Sure and thanks, @nith2001.

Please just consider that we are short on capacity and this topic is a corner case, so it may take some time before we can provide feedback.

**Comment by nith2001** [comment]
@scordio Haha, no problem, Jessica and myself are still trying to get more experience before we take on harder issues.

**Comment by nith2001** [comment]
@scordio
What do you think about this:
```
  public SELF isNotEmpty() {
    try {
      if (actual.markSupported()){
        actual.mark(1);
        inputStreams.assertIsNotEmpty(info, actual);
        actual.reset();
      } else {
        inputStreams.assertIsNotEmpty(info, actual);
      }
    } catch (IOException e) {
      e.printStackTrace();
    }
    return myself;
  }
```
The old warning was: <b>Warning: this will consume the first byte of the {@code InputStream}</b>

But I've modified it to this: <b>Warning: this will consume the first byte of the {@code InputStream} if it is not mark-supported.</b>

**Comment by scordio** [comment]
I'd go with:

```
Warning: this will consume the first byte of the {@code InputStream} if the underlying implementation does not support {@link InputStream#markSupported() marking}.
```

About the code snippet, I'd say the mark/reset pair should be pushed down to `InputStreams`, being an implementation detail of the assertions, and the `IOException` in the catch block should be rethrown wrapped in a new `UncheckedIOException`.

Also, I imagine not only `isNotEmpty` consumes the stream but also other assertions like `hasContent`. Maybe a more generic solution could be implementing a wrapper method accepting a `Runnable` and dealing with mark/reset around its execution, where the marking size could be derived by the `expected` object.

**Comment by jessicant** [comment]
@scordio prototyping - please excuse that the catch is not wrapped into a new `UncheckedIOException`

So at the lower level would you want us to do something like this:

`  public void assertHasDigest(AssertionInfo info, InputStream actual, String algorithm, String expected) {
    requireNonNull(expected, "The string representation of digest to compare to should not be null");
    tryStreamReset(() -> assertHasDigest(info, actual, algorithm, Digests.fromHex(expected)), actual);
  }
  private void tryStreamReset(Runnable runnable, InputStream actual) {
    try {
      if (actual.markSupported()){
        actual.mark(1);
        runnable.run();
        actual.reset();
      } else {
        runnable.run();
      }
    } catch (IOException e) {
      e.printStackTrace();
    }
  }
}
`

Let me know if I am misunderstanding.

**Comment by scordio** [comment]
@jessicant yes, I had roughly this in mind. Maybe an additional parameter is needed for the `readLimit` of `mark`, probably 1 is not enough in case of some assertions like `hasContent`.

**Comment by jessicant** [comment]
@scordio glad we're on the right track. Do you have idea for how to implement that readLimit variable in a dynamic fashion? @nith2001 and I are not sure how to supply the correct amount of bytes to the method. The current idea is just setting that to 'Integer.MAX_VALUE' but that seems like a very naive implementation and regardless it fails tests (likely for the readLimit being set too high).

Thank you for your help and patience - we are still learning how to contribute effectively to larger projects :-)

**Comment by scordio** [comment]
No worries, @jessicant, and thank you both for spending time on it! Feel free to raise a draft PR and we could brainstorm together over there about the next steps.
