### ISSUE TITLE
assertContainsIgnoringCase fails to compare i and I in tr_TR locale

### ISSUE THREAD

**Issue by vlsi** [assertj/assertj#2666]
See `org.assertj.core.internal.Strings#assertContainsIgnoringCase`

https://github.com/assertj/assertj-core/blob/9051a958e6ab0a750bb243060aef57001ab97e6e/src/main/java/org/assertj/core/internal/Strings.java#L528-L531

I would suggest adding https://github.com/policeman-tools/forbidden-apis verification to just ban `toLowerCase()`, `toUpperCase()` and other unsafe methods: https://github.com/assertj/assertj-core/issues/2664

**Comment by scordio** [comment]
Reopening as licensing/work attribution aspects are open (see #2688).
