### ISSUE TITLE
Assertj must include commons-lang3 copyright notice to comply with its license

### ISSUE THREAD

**Issue by vlsi** [assertj/assertj#2688]
**Describe the bug**

https://github.com/assertj/assertj-core/pull/2685 introduced code borrowed from `org.apache.commons.lang3`, so you must include NOTICE in both source and binary re-distributions of assertj (see https://github.com/apache/commons-lang/blob/master/NOTICE.txt, https://github.com/apache/commons-lang/blob/master/LICENSE.txt#L37-L38).

**Comment by scordio** [comment]
Thanks for raising this, @vlsi.

Adding a `NOTICE` file is not a problem from my point of view, but we could also have a custom and simpler implementation as we don't target all the use cases `commons-lang` supports.

**Comment by scordio** [comment]
Hi @khmarbaise, may I ask your opinion about this topic?

To solve #2685, we've taken some methods from `commons-lang` and added them to the AssertJ codebase:

https://github.com/assertj/assertj-core/blob/befef07f172031847cbdd7a7e0622d52a64a9033/src/main/java/org/assertj/core/internal/Strings.java#L1360-L1445

Both AssertJ and `commons-lang` are licensed as Apache 2.0. Would a `NOTICE` file with the following statement be enough to properly recognize the work attribution?

```
This product includes software developed at
The Apache Software Foundation (https://www.apache.org/).
```

**Comment by vlsi** [comment]
>Would a NOTICE file with the following statement be enough to properly express the work attribution?

One more thing is to add would be adding the following to the source redistribution of AssertJ https://github.com/apache/commons-lang/blob/master/src/main/java/org/apache/commons/lang3/StringUtils.java#L2-L15 (e.g. assertj-core-...-source.jar on Central)

**Comment by khmarbaise** [comment]
Sorry for the late response... my personal opinion is this is sufficient. Yes... but I'm not a lawyer...

**Comment by scordio** [comment]
`commons-lang` code is no longer used.
