### ISSUE TITLE
Throw org.opentest4j.AssertionFailedError for containsExactly

### ISSUE THREAD

**Issue by vlsi** [assertj/assertj#2697]
#### Feature summary

Throw `org.opentest4j.AssertionFailedError` for `org.assertj.core.api.AbstractIterableAssert#containsExactly` failures so IDEs would show `<Click to see difference>` feature.

I think it is a sub-task of https://github.com/assertj/assertj-core/issues/1335, however, #1335 looks too broad to ever finished, so I suggest creating sub-tasks.

I suggest adding a task list to #1335 as described in https://docs.github.com/en/issues/tracking-your-work-with-issues/about-task-lists#creating-task-lists

#### Example

```java
assertThat(java.util.Arrays.asList("world", "hello")).containsExactly("hello", "world");
```

**Comment by ChrisZoet** [comment]
Hey, can I make an attempt to work this out?
