### ISSUE TITLE
Add extracting()/returns() method to most assertions

### ISSUE THREAD

**Issue by fishautumn** [assertj/assertj#2712]
#### Feature summary

when testing a spring-data-jpa application, I found `org.assertj.core.api.Assertions.assertThat(org.springframework.data.domain.Page)` returns `IterableAssert` which has no `extracting()` and `returns()` method.

I have to use `org.assertj.core.api.Assertions#assertThatObject`.

In Java world, `Iterable` implement instances are all expected to be `Object`, so can we add method `extracting` and `returns` (maybe some more) functions to `IterableAssert`? It should make writing unittest more easy.

**Comment by joel-costigliola** [comment]
@fishautumn do you have a concrete use case where `extracting` would be need for the iterable under test itself (as opposed to its elements) ?

We already have [extracting](https://www.javadoc.io/static/org.assertj/assertj-core/3.23.1/org/assertj/core/api/AbstractIterableAssert.html#extracting(java.util.function.Function)) defined for iterables assertion that operates on the elements.

**Comment by fishautumn** [comment]
> @fishautumn do you have a concrete use case where `extracting` would be need for the iterable under test itself (as opposed to its elements) ?
> 
> We already have [extracting](https://www.javadoc.io/static/org.assertj/assertj-core/3.23.1/org/assertj/core/api/AbstractIterableAssert.html#extracting(java.util.function.Function)) defined for iterables assertion that operates on the elements.

Oh, I haven't noticed that. So `returns` is the only method I really need.

**Comment by scordio** [comment]
Can you please provide a concrete use case? `returns` is usually used to verify bean properties. What would you verify with `returns` on an `Iterable`?

**Comment by fishautumn** [comment]
Some `Iterable` implementations may have properties.

I'm working on a spring-data-jpa application. A method may have return type of `org.springframework.data.domain.Page<T>`, which has properties: `totalPages`, `totalElements`.

My test is something like this:
```java
assertThat(myRepository.findAll(PageRequest.ofSize(10)))
  .returns(3, Page::getTotalPages)
  .returns(25, Page::getTotalElements)
  .hasSameElementsAs(Arrays.asList(e1, e2, e3, ... e10));
```

**Comment by scordio** [comment]
Although it's true that all types extend from `Object`, we try to expose type-specific and meaningful assertions that can be more powerful and expressive than a simple `returns`.

I tend to see `returns` as not useful for most of the `Iterable` use cases, so I'd avoid polluting the API.

Would the following be an option?

```java
Page<?> page = myRepository.findAll(PageRequest.ofSize(10));

assertThat(page.getTotalPages()).isEqualTo(3);
assertThat(page.getTotalElements()).isEqualTo(25);
assertThat(page).hasSameElementsAs(Arrays.asList(e1, e2, e3, ... e10));
```

Using `getContent` might also give more expressive assertions, similar to [what the project uses](https://github.com/spring-projects/spring-data-jpa/blob/1fc9c2529b9c4b7ffa05310aa8a66f4991f2b30c/spring-data-jpa/src/test/java/org/springframework/data/jpa/repository/UserRepositoryTests.java#L1718-L1723) in their own tests.

**Comment by fishautumn** [comment]
Yes, it works. I'm using `assertThatObject(...).returns(...)`.

I agree that `returns` is not useful for most `Iterable`. This is the first and the only case I met.

**Comment by joel-costigliola** [comment]
@fishautumn is there anything else you need from us or can we close this issue?

**Comment by fishautumn** [comment]
All my questions are get answered. Thanks for all of your reponse.
