### ISSUE TITLE
Support for GString in `Assertions.registerFormatterForType`

### ISSUE THREAD

**Issue by nstdio** [assertj/assertj#2734]
When registering custom formatter in Groovy and using the interpolated string we are getting `ClassCastException` on [StandarardRepresentation:311](https://github.com/assertj/assertj/blob/main/assertj-core/src/main/java/org/assertj/core/presentation/StandardRepresentation.java#L311) because we are trying to cast `GStringImpl` to `String`.

Here is the simple Spock spec to demonstrate this:

```groovy
import org.assertj.core.api.Assertions
import spock.lang.Specification

class SomeSpec extends Specification {
    def setupSpec() {
        Assertions.registerFormatterForType(Long) { "\$$it\$" }
    }

    def "should fail"() {
        expect:
        Assertions.assertThat(1L).isEqualTo(2L)
    }
}
```

There are two straightforward workarounds for this issue:

- Explicitly invoking `toString` on interpolated string like: `{ "\$$it\$".toString() }`
- Using plain concatenation: `{'$' + it + '$'}`

If you interested in this change, I would like to contribute the patch.

**Comment by scordio** [comment]
Sure, @nstdio. If you have already an idea on how to support this use case, feel free to create a PR!

I think it would be helpful if we could also add dedicated Groovy tests to prevent regressions. However, AssertJ is not yet ready for it and I personally don't have first-hand experience with Groovy + Maven + JUnit.

With a quick search, I've found the [`gmavenplus-plugin`](https://github.com/groovy/GMavenPlus) so something might be possible with it. Let's evaluate that during the PR review.

**Comment by nstdio** [comment]
I've been thinking about 2 possibilities to solve this issue:

- Change second argument of [StandardRepresentation#registerFormatterForType](https://github.com/assertj/assertj/blob/main/assertj-core/src/main/java/org/assertj/core/presentation/StandardRepresentation.java#L184) to `Function<T, ? extends CharSequence>` and all the appropriate changes in internals. Seems this would not brake backwards compatibility with existing code.
- Leave public API untouched and handle the case in [StandarardRepresentation:311](https://github.com/assertj/assertj/blob/main/assertj-core/src/main/java/org/assertj/core/presentation/StandardRepresentation.java#L311), namely avoid direct casting to string, rather checking `instanceof CharSequence`.
