### ISSUE TITLE
usingRecursiveComparison() ignores overridden equals() rules

### ISSUE THREAD

**Issue by extryd** [assertj/assertj#2744]
**Describe the bug**
I faced the issue that usingRecursiveComparison() doesn't consider the overridden equals() method.

I copied the code from doc example and it fails for me as well 
https://assertj.github.io/doc/#assertj-core-recursive-comparison-ignoring-equals

* assertj core version: 3.23.1
* java version: 11.0.9
* test framework version: TestNg 7.5
* os (if relevant): 

**Test case reproducing the bug**
I just copied the code from doc example (only constructor was added)

```
    public class Person {
        Person (String name, double height) {
            this.name = name;
            this.height = height;
        }
        String name;
        double height;
        Home home = new Home();
    }

    public class Home {
        Address address = new Address();
    }

    public static class Address {
        int number;
        String street;

        // only compares number, ouch!
        @Override
        public boolean equals(final Object other) {
            if (!(other instanceof Address)) return false;
            Address castOther = (Address) other;
            return Objects.equals(number, castOther.number);
        }
    }

    public void verifyTestX() {
        Person sherlock = new Person("Sherlock", 1.80);
        sherlock.home.address.street = "Baker Street";
        sherlock.home.address.number = 221;

        Person sherlock2 = new Person("Sherlock", 1.80);
        sherlock2.home.address.street = "Butcher Street";
        sherlock2.home.address.number = 221;

        // assertion succeeds but that's not what we expected since the home.address.street fields differ
// but the equals implementation in Address does not compare them.
        Assertions.assertThat(sherlock).usingRecursiveComparison()
                .isEqualTo(sherlock2);
    }
```

But it fails actually with
```
field/property 'home.address.street' differ:
- actual value  : "Baker Street"
- expected value: "Butcher Street"
```

**Comment by joel-costigliola** [comment]
@extryd the wording in the documentation might be a bit unclear but since 3.17.0 the recursive comparison ignores all overridden equals methods (except for java types).
**Before** 3.17.0,  it used overridden equals methods and it was possible to ignore some by type or regex.

The doc is confusing because the examples only work for version < 3.17.0 which can be enabled by https://www.javadoc.io/static/org.assertj/assertj-core/3.23.1/org/assertj/core/api/RecursiveComparisonAssert.html#usingOverriddenEquals().

Does that answer your question/issue?

**Comment by extryd** [comment]
@joel-costigliola oh I see, I thought the example is for the actual behaviour. Thank you for the clarification.
