### ISSUE TITLE
Integration test infrastructure for Kotlin

### ISSUE THREAD

**Issue by scordio** [assertj/assertj#2757]
Related to #2424, we should add a new `assertj-core-kotlin` module under [assertj-tests/assertj-integration-tests](https://github.com/assertj/assertj/tree/main/assertj-tests/assertj-integration-tests) to support Kotlin based integration tests.

We could check the [Kotlin related issues](https://github.com/assertj/assertj/issues?q=label%3A%223rd-party%3A+Kotlin%22) we had in the past to see if any Kotlin specific test case can be added.

**Comment by sreenath-tm** [comment]
I'm interested in contributing to this issue, so before I start working it, would you mind sparing your time explaining what the fix will be and pointing me to some resources to get started.

**Comment by scordio** [comment]
Hi @sreenath-tm, thanks for the help!

The idea would be to add a new Maven module called `assertj-core-kotlin`. The module should be a child module of [assertj-integration-tests](https://github.com/assertj/assertj/blob/a4e709ce2acd466a84affbbd61949db1dd8bf44b/assertj-tests/assertj-integration-tests/pom.xml). This module should have only a `src/test/kotlin` folder, should be capable to compile Kotlin test source files and should execute them with JUnit Jupiter.

You might take inspiration from #2758 which added support for Groovy.

About the needed Maven config, in case you use IntelliJ, a new Kotlin-based Maven project might provide some inspiration. [`junit5-jupiter-starter-maven-kotlin`](https://github.com/junit-team/junit5-samples/tree/main/junit5-jupiter-starter-maven-kotlin) might also be helpful.

In terms of tests to add, you could start with something similar to [Assertions_assertThat_with_Groovy_strings_Test](https://github.com/assertj/assertj/blob/main/assertj-tests/assertj-integration-tests/assertj-core-groovy/src/test/groovy/org/assertj/core/tests/groovy/Assertions_assertThat_with_Groovy_strings_Test.groovy), where Kotlin specific syntax is used.

As we run our CI with all the newest versions of Java, including early access ones like 19 and 20, you might need to check if the latest Kotlin version supports all of them. The easiest way could be to create a draft PR and see if all the CI jobs are succeeding. If there are problems with certain versions, Maven profiles might help in this direction, similarly to [what we have with Groovy](https://github.com/assertj/assertj/blob/a4e709ce2acd466a84affbbd61949db1dd8bf44b/assertj-tests/assertj-integration-tests/pom.xml#L22-L32) which doesn't support Java 20 yet.
