### ISSUE TITLE
isEqualsIgnoringNewLines failes

### ISSUE THREAD

**Issue by ccsoftno** [assertj/assertj#2761]
**Describe the bug**
isEqualsIgnoringNewLines dosn't work on escape strings, since \\\r\\\n doesn't match \\r\\n...

* assertj core version: all after isEqualsIgnoringNewLines
* java version: any
* test framework version: any
* os (if relevant): Windows vs Linux newLines

**Test case reproducing the bug**
Test it with escaped strings, then \\r\\n doesn't match replace("\r\n", "\n")

Add a test case showing the bug that we can run

```java
assertThat("test\\r\\n test2").isEqualToIgnoringNewLines("test\n test2");
```

**Comment by scordio** [comment]
Having `"\\n"` in a string does not represent an escaped version of "\n" but it's actually two characters, `\` and `n`.

Invoking `toCharArray()` also shows this:

![Screenshot 2022-09-01 at 23 29 27](https://user-images.githubusercontent.com/26772046/188016659-d7c20eaa-e6d0-4c95-9db4-3ed65cbdb1cb.png)

So the assertion is correctly failing.

I'm going to reject this issue but please let me know if I missed anything.
