### ISSUE TITLE
Make error msg for asserting Tuple easier to copy into code

### ISSUE THREAD

**Issue by RG9** [assertj/assertj#2768]
#### Example & feature description

```java
    @Test
    void test() {
        List<Foo> actual = List.of(
            new Foo(1, 1, 1),
            new Foo(2, 2, 2));
        assertThat(actual)
            .extracting(Foo::x, Foo::y)
            .containsExactly(); // empty in order to fail and show error msg
    }

    record Foo(int x, int y, int z) {

    }

```
Output is:
```
java.lang.AssertionError: 
Expecting actual:
  [(1, 1), (2, 2)]
to contain exactly (and in same order):
  []
but some elements were not expected:
  [(1, 1), (2, 2)]
```

Would be nice to have:
```
java.lang.AssertionError: 
Expecting actual:
  [tuple(1, 1), tuple(2, 2)]
to contain exactly (and in same order):
  []
but some elements were not expected:
  [tuple(1, 1), tuple(2, 2)]
```  
so I could easily copy `tuple(1, 1), tuple(2, 2)` into `.containsExactly(..)`.

What do you think? 
Is it easy to implement?
Or is there any nice workaround?

**Comment by scordio** [comment]
You could create your own representation:

```java
class CustomRepresentation extends org.assertj.core.presentation.StandardRepresentation {
    @Override
    protected String toStringOf(Tuple tuple) {
      return "tuple" + super.toStringOf(tuple);
    }
  }
```

and use it in [`withRepresentation`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/Assert.html#withRepresentation(org.assertj.core.presentation.Representation)):

```java
assertThat(actual)
    .withRepresentation(new CustomRepresentation())
    .extracting(Foo::x, Foo::y)
    .containsExactly(); // empty in order to fail and show error msg
```

The output would be:

```
java.lang.AssertionError: 
Expecting actual:
  [tuple(1, 1), tuple(2, 2)]
to contain exactly (and in same order):
  []
but some elements were not expected:
  [tuple(1, 1), tuple(2, 2)]
```

**Comment by RG9** [comment]
Thanks @scordio! 

How about making this representation a default one?

**Comment by scordio** [comment]
`Tuple` is currently rendered as other iterables and I personally don't see the prefix as generally useful, so I'd prefer to keep the current representation knowing it can be customized as in the example above.

@assertj/core thoughts?

**Comment by joel-costigliola** [comment]
I prefer it without the prefix, it focuses more on the data than the data structure, similar to representing an array as `[1,2,3]` and not `array[1,2,3]` or `array(1,2,3)`
