### ISSUE TITLE
Improve null-safety of isEqualToNormalizingNewlines

### ISSUE THREAD

**Issue by rweisleder** [assertj/assertj#2775]
AssertJ version: 3.23.1
Java version: 17

When comparing strings with isEqualToNormalizingNewlines, the handling of `null` can be improved.

### Example 1

```java
@Test
void compare_null_and_null() {
    String actual = null;
    String expected = null;
    assertThat(actual).isEqualToNormalizingNewlines(expected);
}
```

I would expect this test to succeed since `null == null` and `assertThat(actual).isEqualTo(expected)` succeeds. Instead, it throws a NullPointerException:
```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "actual" is null

	at org.assertj.core.internal.Strings.normalizeNewlines(Strings.java:681)
	at org.assertj.core.internal.Strings.assertIsEqualToNormalizingNewlines(Strings.java:673)
	at org.assertj.core.api.AbstractCharSequenceAssert.isEqualToNormalizingNewlines(AbstractCharSequenceAssert.java:1692)
	at de.rweisleder.DemoTest.compare_null_and_null(DemoTest.java:13)
```

### Example 2

```java
@Test
void compare_null_and_empty() {
    String actual = null;
    String expected = "";
    assertThat(actual).isEqualToNormalizingNewlines(expected);
}
```

I would expect this test to fail with `AssertionError: Expecting actual not to be null`. Instead, it throws a NullPointerException same as above.

### Example 3

```java
@Test
void compare_empty_and_null() {
    String actual = "";
    String expected = null;
    assertThat(actual).isEqualToNormalizingNewlines(expected);
}
```

I would expect this test to fail with something like `AssertionError: expected: null, but was: ""`. Instead it throws the same NullPointerException:
```
java.lang.NullPointerException: Cannot invoke "java.lang.CharSequence.toString()" because "actual" is null

	at org.assertj.core.internal.Strings.normalizeNewlines(Strings.java:681)
	at org.assertj.core.internal.Strings.assertIsEqualToNormalizingNewlines(Strings.java:674)
	at org.assertj.core.api.AbstractCharSequenceAssert.isEqualToNormalizingNewlines(AbstractCharSequenceAssert.java:1692)
	at de.rweisleder.DemoTest.compare_empty_and_null(DemoTest.java:27)
```

Notice the misleading "because **"actual"** is null" while in fact **expected** is null. (due to Javas improved NullPointerException in Java 14+)

**Comment by scordio** [comment]
Thanks, @rweisleder!

I agree, these use cases can be improved. Would you like to contribute?

**Comment by marcela-cardona-s** [comment]
Hi @scordio I would like contribute with this issue, can i do it?

**Comment by scordio** [comment]
Hi @marcela-cardona-s, this issue is currently covered by #2776.

**Comment by Ds2994** [comment]
Hi @scordio would #2776 for this issue be integrated ? I had an use case that will benefit from this improvement.

**Comment by scordio** [comment]
Hi @Ds2994, I've put the PR in our next milestone to make sure we'll look at it.

**Comment by joel-costigliola** [comment]
fixed in https://github.com/assertj/assertj/commit/8dfa63ba8cb72991b0f7833f2acad146f077ccb1
