### ISSUE TITLE
isEqualToIgnoringGivenFields now verifies that the fields to ignore exist on the type of objects to compare

### ISSUE THREAD

**Issue by kryger** [assertj/assertj#278]
I was surprised to see that passing non-existent fields to  `assertIsEqualToIgnoringGivenFields()` is quietly ignored. In my case I made a typo: I wanted to exclude `dateVerified` but I mistyped it as `dateVerfied`. The test failed for an unexpected reason and it took me a little bit of time to realise what happened.
I felt that a situation like this would always indicate user error, so I patched this behaviour:

New test case in `Objects_assertIsLenientEqualsToByIgnoringNullFields_Test`:

```
  @Test
  public void should_fail_when_asked_to_ignore_non_existent_fields() {
    thrown.expect(SomeYetToBeNamedException.class, "Declared fields to ignore not found on the target object");

    AssertionInfo info = someInfo();
    Jedi actual = new Jedi("Yoda", "Green");
    Jedi other = new Jedi("Yoda", "Green");
    objects.assertIsEqualToIgnoringGivenFields(info, actual, other, "no-such-field");
  }
```

New implementation of `Objects.assertIsEqualToIgnoringGivenFields`:

```
  private <A> ByFieldsComparison isEqualToIgnoringGivenFields(A actual, A other, String[] fields) {
    List<String> fieldsNames = new LinkedList<String>();
    List<Object> expectedValues = new LinkedList<Object>();
    List<Object> rejectedValues = new LinkedList<Object>();
    Set<String> ignoredFields = newLinkedHashSet(fields);
    for (Field field : getDeclaredFieldsIncludingInherited(actual.getClass())) {
      try {
        if (!ignoredFields.contains(field.getName())) {
          Object actualFieldValue = getFieldOrPropertyValue(actual, field);
          Object otherFieldValue = getFieldOrPropertyValue(other, field);
          if (!org.assertj.core.util.Objects.areEqual(actualFieldValue, otherFieldValue)) {
            fieldsNames.add(field.getName());
            rejectedValues.add(actualFieldValue);
            expectedValues.add(otherFieldValue);
          }
          // ADDITION 1
          ignoredFields.remove(field.getName());
        }
      } catch (IntrospectionError e) {
        // Not readable field, skip.
      }
    }

    // ADDITION 2
    if (!ignoredFields.isEmpty()) {
      throw new SomeYetToBeNamedException("Declared fields to ignore not found on the target object:" + ignoredFields);
    }
    return new ByFieldsComparison(fieldsNames, expectedValues, rejectedValues);
  }
```

This change, however, breaks 6/10 tests in `Objects_assertIsLenientEqualsToByIgnoringFields_Test` which obviously suggests that the "silently ignore invalid fields" behaviour was actually intended.
Why would anyone ever need this to work this way in practice? Are there any edge cases I'm forgetting about? Would it be worth changing this behaviour? (i.e. apply the change suggested and adapt the failing tests to the new behaviour)

**Comment by natnan** [comment]
Today, this change broke a few of our tests because we were using it in a common test method where we compare similar objects with different properties (hard to explain). In one of the classes we need to ignore a specific field which isn't included in the other similar classes. Since we don't want to copy-paste this common method all around (some might disagree) we added the ignored field name into this common method.

I've just explained this as an example that was lacking in this issue, not as a complaint :). I think it'd be good to be able to skip this verification.
