### ISSUE TITLE
`OptionalAssert#get()` with `SoftAssertions` throws `NoSuchElementException`

### ISSUE THREAD

**Issue by brandoncimino** [assertj/assertj#2784]
Using `OptionalAssert#get()` with `SoftAssertions` throws a `NoSuchElementException`, which breaks all everything else in the `SoftAssertions`.

* assertj core version: 3.23.1
* java version: 11 _(Amazon Corretto 11.0.10_9)_
* test framework version: TestNG 7.3.0

## Test case reproducing the bug

```java
@Test
public void optionalSoftAssertion() {
    Optional<String> empty = Optional.empty();
    
    SoftAssertions.assertSoftly(softly -> {
        softly.assertThat(0).isEqualTo(1);
        softly.assertThat(empty).get();
    });
}
```

### Expected result:

A `MultipleFailuresError` containing the `.isEqualTo(1)` and `OptionalAssert#get()` failures.

### Actual result:

A `NoSuchElementException`.

**Comment by scordio** [comment]
Thanks for the bug report, @brandoncimino!

This is the same issue identified with `extracting` in #2495 so I'm closing this issue as a duplicate.
