### ISSUE TITLE
Recursive comparison for the fields of given type only

### ISSUE THREAD

**Issue by beyond-danube** [assertj/assertj#2793]
#### Perform recursive comparison on fields of given type only
`.usingRecursiveComparison()` is really helpful in the number of cases, especially when comparing huge composite objects. 
  
For some cases, when only part of object should be compared `comparingOnlyFields` is a good option, however there are cases when filed name could change, or another that we would need to compare added. Comparing fields of particular type e.g. `compareOnlyFieldsOfTypes` would resolve this.

Combining it with existing `ignoreFieldsOfTypes` would simplify a lot of cases e.g. compare only fields of `Person.class` which is a filed of parent object (let's say `Order.class`), but skip `UUID.class` for person. Person's only fields will be compared, with possible additional filtering.

#### Example

```java
assertThat(actual).usingRecursiveComparison()
                    .comparingOnlyFieldsOfTypes(Person.class)
                    .ignoreFieldsOfTypes(UUID.class)
                    .isEqualTo(expected);
```

**Comment by joel-costigliola** [comment]
Thanks, I will review your PR in the next few days

**Comment by joel-costigliola** [comment]
Addressed by https://github.com/assertj/assertj/commit/0b0ce5d88ec831fb55daf9bc1aa5894e29f63e7a
