### ISSUE TITLE
(very) small error in javadoc of : org.assertj.core.api.Assertions#within(long, java.time.temporal.TemporalUnit)

### ISSUE THREAD

**Issue by remika** [assertj/assertj#2799]
There is a small error in the java doc of org.assertj.core.api.Assertions#within(long, java.time.temporal.TemporalUnit)
"Assertions entry point for TemporalUnitOffset with with less than or equal condition to use with isCloseTo temporal assertions."

"with" is doubled

* assertj core version: 3.7.0

**Comment by joel-costigliola** [comment]
Good catch, thanks for reporting this @remika!
