### ISSUE TITLE
Make the assertion lambdas Kotlin friendly

### ISSUE THREAD

**Issue by OndraZizka** [assertj/assertj#2821]
#### Feature summary
Some assertions accept a functor:
```java
public static <THROWABLE extends Throwable> THROWABLE catchThrowableOfType(ThrowingCallable shouldRaiseThrowable,
                                                                             Class<THROWABLE> type) {
    return AssertionsForClassTypes.catchThrowableOfType(shouldRaiseThrowable, type);
  }
```

Kotlin has a syntax for lambdas, so it could call:
```kotlin
catchThrowableOfType(NotFoundException::class.java) { 
    connectionService.findBy(hubId = "hub2", connId = "conn1") 
}
```
But as it is, it needs to stick with the less readable:
```kotlin
catchThrowableOfType( { 
    connectionService.findBy(hubId = "hub2", connId = "conn1") 
}, NotFoundException::class.java)
```
Could you please add some overrides, moving the functors to the last place? Like,

```java
public static <THROWABLE extends Throwable> THROWABLE catchThrowableOfType(
         Class<THROWABLE> type, ThrowingCallable shouldRaiseThrowable) {
    return AssertionsForClassTypes.catchThrowableOfType(shouldRaiseThrowable, type);
  }
```

Thanks for considering.

AssertJ 3.23.1

**Comment by OndraZizka** [comment]
One more thing: `isNull`  could return a boolean. Because then, Kotlin considers that a getter, and needs no `()` to invoke it:

```kotlin
        assertThat( connectionRepo.findByToken(updateData.authToken)).isNotNull
        assertThat( connectionRepo.findByToken("non-existent")).isNull()
```

**Comment by java-coding-prodigy** [comment]
Could I take on this?

**Comment by scordio** [comment]
Hi @java-coding-prodigy, thanks for the offer. Please, give us a bit of time to analyze the issue and have a decision from the team.

**Comment by java-coding-prodigy** [comment]
> Hi @java-coding-prodigy, thanks for the offer. Please, give us a bit of time to analyze the issue and have a decision from the team.

Sure thing

**Comment by scordio** [comment]
**Team decision**: let's add `catchThrowableOfType(Class<THROWABLE>, ThrowingCallable)` and deprecate the existing `catchThrowableOfType(ThrowingCallable, Class<THROWABLE>)`.

We believe that the readability of Java code can also benefit from this change.

@java-coding-prodigy would you like to take care of these changes?

**Comment by java-coding-prodigy** [comment]
> **Team decision**: let's add `catchThrowableOfType(Class<THROWABLE>, ThrowingCallable)` and deprecate the existing `catchThrowableOfType(ThrowingCallable, Class<THROWABLE>)`.
> 
> We believe that the readability of Java code can also benefit from this change.
> 
> @java-coding-prodigy would you like to take care of these changes?

Yes I am ready to make those changes
I assume we will also replace existing calls of the method in our repo?

**Comment by scordio** [comment]
> I assume we will also replace existing calls of the method in our repo?

Yes, that would make sense.
