### ISSUE TITLE
Refrain from using `Failures#failure(AssertionInfo, ErrorMessageFactory)` since it misses <click to see difference> in IDE

### ISSUE THREAD

**Issue by vlsi** [assertj/assertj#2885]
#### Feature summary

AssertJ should prefer failures that produce `<click to see difference>` in IDEs.

It turns out, there's a number of assertions that do not provide expected and actual object, so `<click to see diff>` is not there.

I guess the root cause is `org.assertj.core.internal.Failures#failure(org.assertj.core.api.AssertionInfo, org.assertj.core.error.ErrorMessageFactory)` method.

So I suggest marking the method as `@Deprecated` or `@Beta`, so **any** usage of the method require an explicit opt-in.

#### Example

Suppose there are two files:

`file1`:

```
line1
line2
line3
```

`file2`:

```
line1
line2
line3
```

```java
assertThat(new File("file1")).hasSameTextualContentAs(new File("file2"));
```

Actual failure:
```
java.lang.AssertionError: 
File:
  /.../file1
and file:
  /.../file2
do not have same content:

Changed content at line 2:
expecting:
  ["line1"]
but was:
  ["line2"]
```

Frankly speaking, I find "changed content at line 2" to be not very helpful.

---

If I try reading text, then it gets better:

```kotlin
assertThat(File("file1").readText())
    .isEqualTo(File("file2").readText())
```

```
expected:<"line1
line[1]
line3
"> but was:<"line1
line[2]
line3
">
<Click to see difference>
```

**Comment by joel-costigliola** [comment]
I agree that having visual difference helps, I'm happy to accept improvements in this area by passing actual and expected and building a subclass of AssertionError that accepts them.

There are quite a lot of places that could be improved, I would prefer we do it one at a time so that each PR is small

**Comment by scordio** [comment]
Relates to #1335.

**Comment by joel-costigliola** [comment]
closing it in favor of https://github.com/assertj/assertj/issues/1335
