### ISSUE TITLE
NullPointerException when expecting null in .returns and .doesNotReturn

### ISSUE THREAD

**Issue by ines-exner** [assertj/assertj#2901]
**Describe the bug**
When I try to use AbstractObjectAssert::returns and I want to check that the function I pass returns null for something, the test throws a NullPointerException:
java.lang.NullPointerException
	at org.assertj.core.api.AbstractObjectAssert.returns(AbstractObjectAssert.java:1105)

The same thing also happens for doesNotReturn.

* assertj core version: 3.24.0
* java version: 11
* test framework version: jUnit 5
* os (if relevant): no

**Test case reproducing the bug**

Add a test case showing the bug that we can run

```java
import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class TestReturns {
    class TestObject {
        final String a;
        TestObject(final String a) {
            this.a = a;
        }

        String getA() {
            return a;
        }
    }

    @Test
    void getA_should_return_null() {
        final TestObject objectUnderTest = new TestObject(null);
        assertThat(objectUnderTest).returns(null, TestObject::getA);
    }

    @Test
    void getA_should_not_return_null() {
        final TestObject objectUnderTest = new TestObject("astring");
        assertThat(objectUnderTest).doesNotReturn(null, TestObject::getA);
    }
}
```

**Comment by scordio** [comment]
Thanks for the bug report, @ines-exner. This is a regression caused by #2725. I'll look into it.

**Comment by ines-exner** [comment]
I've also looked into this and it's this line that throws: `Objects objects = getComparatorBasedObjectAssertions(expected.getClass());` (expected is null in our usecase)
This could be fixed by doing something like this instead:

```java
  public <T> SELF doesNotReturn(T expected, Function<ACTUAL, T> from) {
    requireNonNull(from, "The given getter method/Function must not be null");
    Objects objects = getComparatorBasedObjectAssertions(expected);
    objects.assertNotEqual(info, from.apply(actual), expected);
    return myself;
  }

  private <T> Objects getComparatorBasedObjectAssertions(T valueOfType) {
    if (valueOfType == null) {
      return objects;
    }
    final Class<?> type = valueOfType.getClass();
    TypeComparators comparatorsByType = getComparatorsByType();
    if (comparatorsByType.hasComparatorForType(type)) {
      return new Objects(new ComparatorBasedComparisonStrategy(comparatorsByType.getComparatorForType(type)));
    }
    return objects;
  }

```

**Comment by scordio** [comment]
Thanks again and sorry for the oversight, we should have had such a simple test case 😓 

I'm going to release 3.24.1 soon.

**Comment by scordio** [comment]
@ines-exner 3.24.1 is now [available](https://repo.maven.apache.org/maven2/org/assertj/assertj-core/3.24.1/).

**Comment by ines-exner** [comment]
Worked perfectly, thanks a lot for the quick response :+1:
