### ISSUE TITLE
NPE using contains on Guava SetView

### ISSUE THREAD

**Issue by TakiuGit** [assertj/assertj#2906]
Hello I'm facing an NPE using `contains` on guava `com.google.common.collect.Sets.SetView`, also present in `3.24.0`.

It was working well on `3.23.1`

* assertj core version: 3.24.1
* java version: corretto-11.0.17
* test framework version: Junit 4.13.2
* guava version : [31.1-jre](https://mvnrepository.com/artifact/com.google.guava/guava/31.1-jre)

```java
import com.google.common.collect.Sets;
import org.assertj.core.api.Assertions;
import org.assertj.core.api.BDDAssertions;
import org.junit.Test;

import java.util.Collections;
import java.util.Set;

public class AssertJCoreIssue {

    @Test
    public void should_pass_contains() {
        //GIVEN
        Set<String> set1 = Collections.singleton("123");
        Set<String> set2 = Collections.singleton("456");

        //WHEN
        Sets.SetView<String> guavaSet = Sets.union(set1, set2);

        //THEN
        BDDAssertions.then(guavaSet).contains("123"); // NPE
        Assertions.assertThat(guavaSet).contains("123"); // NPE
    }
}
```

**Comment by dsw2127** [comment]
Seeing this as well, caused by the check added in https://github.com/assertj/assertj/issues/2134 as `getCanonicalName()` on the resulting Class of `Sets.union` returns `null` as it is an anonymous class.

**Comment by dsw2127** [comment]
This can be worked around by doing, for example, `Assertions.assertThat(java.util.Set.copyOf(guavaSet)).contains("123");`

**Comment by scordio** [comment]
Thanks for the details, @TakiuGit and @dsw2127. I plan to work on it and release a fix by the end of the week.
