### ISSUE TITLE
`containsOnlyDigits()` was deprecated without alternative in `3.24.1`

### ISSUE THREAD

**Issue by armandino** [assertj/assertj#2908]
Not a bug, but a question. The string assertion `containsOnlyDigits()` has been marked as deprecated in commit 88e252e5a9. There doesn't seem to be an alternative method and no mention of this in the release notes.

Was this an intentional change? If so, what method should be used instead?

* assertj core version: `3.24.1`

**Comment by scordio** [comment]
Thanks for raising this, @armandino.

Unfortunately, this was an oversight. As mentioned in https://github.com/assertj/assertj/issues/2472#issuecomment-1204519079:

> The existing `containsOnlyDigits` will not be deprecated.

We'll make sure to remove the `@Deprecated` annotation in the next release.

**Comment by armandino** [comment]
Thanks for confirming, @scordio. That's what I suspected :) 

I created a PR to remove the deprecation.
