### ISSUE TITLE
Illegal reflective access when recursively comparing XMLGregorianCalendar

### ISSUE THREAD

**Issue by lcharrie** [assertj/assertj#2928]
**assertThat().usingRecursiveComparison() on XMLGregorianCalendar objects triggers an illegal reflective access operation**

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.assertj.core.util.introspection.FieldUtils (file:/home/lc22j176/.m2/repository/org/assertj/assertj-core/3.24.2/assertj-core-3.24.2.jar) to field com.sun.org.apache.xerces.internal.jaxp.datatype.XMLGregorianCalendarImpl.orig_second
WARNING: Please consider reporting this to the maintainers of org.assertj.core.util.introspection.FieldUtils
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

* assertj core version 3.24.2
* java 14
* junit-jupiter-api version 5.8.2

**Test case reproducing the bug**

```java
  void AssertjXMLGregorianCalendarTest() throws Exception {

    XMLGregorianCalendar in = DatatypeFactory.newInstance().newXMLGregorianCalendar();
    XMLGregorianCalendar out = DatatypeFactory.newInstance().newXMLGregorianCalendar();

    assertThat(out).usingRecursiveComparison().isEqualTo(in);
  }
```

**Comment by scordio** [comment]
I'd say we also consider `javax` for Java types detection in [`DualValue`](https://github.com/assertj/assertj/blob/9739d6995940b3cef37c9c99e6bd3d62ea84b704/assertj-core/src/main/java/org/assertj/core/api/recursive/comparison/DualValue.java#L111-L115).

@assertj/core do you agree?

**Comment by joel-costigliola** [comment]
Yes, I think anything that AssertJ won't be able to introspect because of java policy to restrict reflective access should be compared by their equals method since there is not much else we can do.

In this case, I could fix the issue by adding `com.sun.*` to java types detection (`javax` did not solve the issue but should be added too).

**Comment by joel-costigliola** [comment]
@lcharrie in the meantime, you can get rid of the warning by telling the recursive comparison to compare `XMLGregorianCalendar` with their `equals` method:
```java
  void AssertjXMLGregorianCalendarTest() throws Exception {

    XMLGregorianCalendar in = DatatypeFactory.newInstance().newXMLGregorianCalendar();
    XMLGregorianCalendar out = DatatypeFactory.newInstance().newXMLGregorianCalendar();

    assertThat(out).usingRecursiveComparison()
                   .withEqualsForType(Objects::equals, XMLGregorianCalendar.class)
                   .isEqualTo(in);
  }
```
