### ISSUE TITLE
Ordering shouldn't matter when comparing Sets

### ISSUE THREAD

**Issue by Tonypsilon** [assertj/assertj#2931]
#### Feature summary
I am not 100% sure if this is a bug or a feature request, but I tend to feature request. I would like to assert that a set `containsExactly` 2 given elements. However, the test fails with `java.lang.AssertionError: Actual and expected have the same elements but not in the same order, (...)`
But for sets, there naturally is no such thing as an "order" and hence it shouldn't matter. One could easily fix the test at hand by using `.containsExactlyInAnyOrder`, but this feels unnatural for a set.

#### First Findings
I did a quick check and found out that a CollectionAssert is acting here. I found that the same package contains a ListAssert, but there is no such thing as a SetAssert. That is what makes me think this is much rather a feature request than a bug.

If anyone decides this would be a good thing to have and this would be a suitable first issue, I could also pick this up myself.

**Comment by scordio** [comment]
There are `Set` implementations where the order matters, e.g. [`LinkedHashSet`](https://docs.oracle.com/javase/7/docs/api/java/util/LinkedHashSet.html).

**Comment by scordio** [comment]
@Tonypsilon I am rejecting this feature request as we try to stay close to the JDK behavior, where [`iterator()`](https://docs.oracle.com/javase/7/docs/api/java/util/Set.html#iterator()) mentions:

> The elements are returned in no particular order (unless this set is an instance of some class that provides a guarantee).

Summarizing:
* [`containsExactly`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractIterableAssert.html#containsExactly(ELEMENT...)) verifies that the input elements appear **in order**, so it should be used with instances that have a consistent iteration order.
* [`containsExactlyInAnyOrder`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractIterableAssert.html#containsExactlyInAnyOrder(ELEMENT...)) verifies that the input elements appear **in any order**.
