### ISSUE TITLE
Consider adding `isPast()` and `isFuture()` methods for asserting dates

### ISSUE THREAD

**Issue by armandino** [assertj/assertj#2932]
#### Feature summary
The new methods would be syntactic sugar for assertions similar to:

```java
assertThat(LocalDate.now().minusDays(1)).isBefore(LocalDate.now());
```

#### Example

```java
assertThat(LocalDate.now().minusDays(1)).isPast();
assertThat(Instant.now().plusSeconds(3)).isFuture();
```

Edit: tasks to track adding `isInThePast()` and `isInTheFuture()`:

- [ ] Instant
- [x] LocalDate
- [ ] LocalDateTime
- [ ] OffsetDateTime
- [ ] ZonedDateTime

**Comment by joel-costigliola** [comment]
We have `isInThePast()` but that's a [date assertion](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractDateAssert.html#isInThePast()) so it would make sense to add them for the date/time introduced in java 8.

**Comment by StefanBratanov** [comment]
Hi @joel-costigliola is it possible to work on this issue?

**Comment by joel-costigliola** [comment]
@StefanBratanov thanks! please pick one of the task and raise a PR for it.

**Comment by armandino** [comment]
Awesome. Thank you @joel-costigliola, and @StefanBratanov for taking this on :)

**Comment by joel-costigliola** [comment]
thanks @StefanBratanov for your contribution.

**Comment by StefanBratanov** [comment]
> thanks @StefanBratanov for your contribution.

No worries. Thank you for maintaining the library. :)
