### ISSUE TITLE
Introduce isNot(After|Before) equivalent to is(Before|After)OrEqual

### ISSUE THREAD

**Issue by onacit** [assertj/assertj#2939]
#### Feature summary

Disclaimer, this is merely a suggestion.

Introduce `isNot(After|Before)` for `TemporalAccessor`-related assertion regarding original method signatures which are equivalent to `is(After|Before)OrEqualTo`.

I'm not sure AssertJ may permit alases for existing assertions yet letting me try.

Let's say the `LocalDate` class (and other classes).
It's been a while, for me, why there is no such method like `isAfterOrRepresentSame` nor `isBeforeOrRepreentSame` just like any other comparison methods in various APIs such as `lt`, `le`, `lessThan` or `lessThanOrEqualTo`. 

There are only `isAfter` and `isBefore`, e.g. in `LocalDate`, and other chrono-related classes.

Anyone would've been figure out that those _OrEqualTo_ functionalities may be achieved by reversing the logic.

```java
LocalDate yesterday = LocalDate.now().minusDays(1L);
LocalDate today = yesterday.plusDays(1L);

yesterDay.isBefore(today); // true
today.isAfter(yesterday) // true

LocalDate someDay = getSome();

// someDay should represent the same day as today or any next day of today.
someDay.isAfter(today) || someDay.equals(today); // seems ok; those equals methods are righteously overridden

// in a reversed term, today should be not before the someDay 
!today.isBefore(someDay); // seems weird, negative(!)|reversed expression, yet may be intended by design. 
```

AssertJ seems have been decided to adding `is(After|Before)OrEqualTo` and they have no problems. Yet combining a chrono-graphic comparison and a logical equivalence seems weird.
(A word of `same` looks better, IMHO.)

It will be (more) helpful when we introduce `isNot(After|Before)` methods besides those methods.

#### Example

```java
LocalDate today = LocalDate.now();
LocalDate someDay = getSome();

// assert someDay represents the same day as today or a day in the future

    | someDay should represent a day in this range including today
----|-----------------------------> t
    today

    | today shouldn't be in this range, excluding someDay 
----|-----------------------------> t
    someDay

assertThat(someDay).isAfterOrEqualTo(today); // existing

assertThat(today).isNotAfter(someDay); // equivalent alias
```

Additional notes,

Above expression may arise arguments about the _actual_ subject that being asserted, `someDay`? or `today`? which, in such case, may be overcame with `as(...)`.

```java
assertThat(today).isNotAfter(someDay)
    .as("someDay(%1$s) compared with today(%2$) regarding ....", someDay, today)
    ;
```

Thank you.

**Comment by joel-costigliola** [comment]
@onacit not completely sure I'm following you, in you example you say both assertions are logically the same:

```java
assertThat(someDay).isAfterOrEqualTo(today); // existing
assertThat(today).isNotAfter(someDay); // equivalent alias
```
but the logical opposite of `isAfterOrEqualTo` is `not after and not equal to` which in this case is exactly `isBefore`. 

I feel avoiding negation in assertion is usually preferable when there is a positive form assertion

**Comment by onacit** [comment]
@joel-costigliola 

Fair enough. Thank you.
> I feel avoiding negation in assertion is usually preferable when there is a positive form assertion

**Comment by joel-costigliola** [comment]
Are you happy we close this issue then?
