### ISSUE TITLE
Add convenient values() extractor method in MapAssert

### ISSUE THREAD

**Issue by Skym0sh0** [assertj/assertj#2978]
#### Feature summary
It would be nice if there was a method in MapAssert that returns a (Abstract)CollectionAssert over the values contained in the map.

Example:
```java
Assertions.assertThat(Map.of("str", 1))
	.values()
	.contains(1);
```

Currently I have to use the following:

```java
Assertions.assertThat(Map.of("str", 1))
	.extracting(Map::values, as(collection(Integer.class)))
	.contains(1);
```

**Comment by joel-costigliola** [comment]
We are ok with this improvement, likely will provide `values()` to switch the object under test to a `Collection<Object>` and `values(Class valueType)` to a `Collection<Class>`.

**Comment by kang-mansher** [comment]
Can I work on this improvement

**Comment by joel-costigliola** [comment]
Sure go ahead @kang-mansher, thanks!

**Comment by igmtz** [comment]
Hello @joel-costigliola can I contribute? 😄

**Comment by joel-costigliola** [comment]
@kang-mansher are you still interested in contributing? if not @igmtz would be keen to.

**Comment by scordio** [comment]
Closing as duplicate of #3291.
