### ISSUE TITLE
usingRecursiveComparison().ignoringFields("fieldName") is not working properly when maps sizes are different

### ISSUE THREAD

**Issue by Anass-ELGHAOUI** [assertj/assertj#2988]
#### Summary
usingRecursiveComparison().ignoringFields("fieldName") is not working properly when comparing two maps with different sizes.

#### Example
using the following code the ingested node will be the same size as the expected one after ignoring "ingestionDate". So I suppose that start comparing the size of the maps makes the method more limited such as in this case for example.
```java
assertThat(ingestedNode).usingRecursiveComparison().ignoringFields("ingestionDate").isEqualTo(expectedNode);
```

**Comment by joel-costigliola** [comment]
Thanks for reporting this @Anass-ELGHAOUI, could provide a test reproducing the issue to help us investigate? thanks!

**Comment by Anass-ELGHAOUI** [comment]
@joel-costigliola yes sure.
```
@Test
  void test_assertj_ignoring_fields() {
    Map<String, Object> mapWithTwoElements =
        Map.ofEntries(entry("firstName", "John"), entry("lastName", "Doe"));
    Map<String, Object> mapWithThreeElements =
        Map.ofEntries(
            entry("firstName", "John"),
            entry("lastName", "Doe"),
            entry("profession", "software Engineer"));
    assertThat(mapWithThreeElements)
        .usingRecursiveComparison()
        .ignoringFields("profession")
        .isEqualTo(mapWithTwoElements);
  }
```

**Comment by JitendraProgrammer** [comment]
Hi I want to join your community so that I can also help you guys
