### ISSUE TITLE
Wiki homepage contains a link to the old website

### ISSUE THREAD

**Issue by thurrox** [assertj/assertj#3033]
The wiki homepage contains a link to the old website, the domain may currently host malware.

Though VirusTotal gave only 1 of 89 positive result, see report https://www.virustotal.com/gui/url/b776db08b1e8ab349331eacde17528c964e46705186297fdbea56195880063e7/detection

My suggestion is to remove the paragraph containing the link.

**Comment by joel-costigliola** [comment]
Thanks for reporting this @thurrox!

**Comment by joel-costigliola** [comment]
Hmm I could not find the link to assertj.org, could you point out wich files contains it?

**Comment by thurrox** [comment]
No problem, the last paragraph on https://github.com/assertj/assertj/wiki

**Comment by joel-costigliola** [comment]
Ah ok, I was looking at the repo home page :sweat_smile:

**Comment by thurrox** [comment]
My bad, should have provided the link on the issue message.

**Comment by joel-costigliola** [comment]
Updated, thanks again.

**Comment by scordio** [comment]
Wiki fully disabled.
