### ISSUE TITLE
usingRecursiveComparison too permissive with smaller class

### ISSUE THREAD

**Issue by Sl4yne** [assertj/assertj#3104]
When comparing 2 kotlin classes with usingRecursiveComparison, it happens that isEqualTo is returning true or false depending on who comes first.

```kotlin
class Test {

    data class OpenAt(val hour: String)
    object Closed

    @Test
    fun `Not passing`() {
        assertThat(OpenAt("10:00"))
            .usingRecursiveComparison()
            .isEqualTo(Closed)
    }

    @Test
    fun `Passing`() {
        assertThat(Closed)
            .usingRecursiveComparison()
            .isEqualTo(OpenAt("10:00"))
    }
}
```

One possibility would be to use withStrictTypeChecking to get around this issue, but I'm not sure the previous behaviour is the one intended. Is it ?

Thanks for your insight.

* assertj core version: 3.24.2

**Comment by Sl4yne** [comment]
Ok so I guess that's the standard behaviour.
Shouldn't `withStrictTypeChecking` be the default behaviour when using `usingRecursiveComparison` ?

**Comment by joel-costigliola** [comment]
It was at some point but we decided otherwise for flexibility.

Even with `withStrictTypeChecking` the recursive comparison is not symmetrical as shown https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/RecursiveComparisonAssert.html#withStrictTypeChecking()
