### ISSUE TITLE
"Is in" assertion randomly fails

### ISSUE THREAD

**Issue by northmaxdev** [assertj/assertj#3127]
**Describe the bug**
When asserting whether a value is contained in an `Iterable` (i.e. using `isIn(Iterable<T>)`), the assertion may or may not randomly fail, even though the `actual` value is, indeed, contained in the `expected` values, which is indicated by:

1. The assertion ocassionally passing without _any_ changes made
2. The logs of the failed assertion

**NOTE:** I am _not_ actually sure this is specifically an AssertJ issue. This very well might be caused by the test framework, some subtle concurrency behavior or something else entirely. That being said, I'd still like to submit this GitHub issue in case it _is_ an AssertJ problem, and apologize if it is not.

* **AssertJ core version:** 3.24.2
* **Java version:** 17
* **Test framework version:** JUnit 5.9.3
* **OS:** Fedora 38 (kernel 6.4.4-200.fc38.x86_64)

**Test case reproducing the bug**

Consider the following utility method:
```java
public static <R extends APIRequest> void assertExpectedURIsContainActual(
        Supplier<R> requestSupplier,
        String... possibleOutcomes) {
    R request = requestSupplier.get();

    Iterable<URI> expected = Arrays.stream(possibleOutcomes)
            .map(URI::create)
            .toList();
    URI actual = request.getURI();

    assertThat(actual).isIn(expected);
}
```
...where `APIRequest`, for the sake of simplicity, can be considered a `@FunctionalInterface` with a `getURI()` method.

Then consider the following JUnit 5 test method:
```java
@Test
void reqURI() {
    assertExpectedURIsContainActual(() -> {
                LocalDate start = LocalDate.of(2020, Month.JANUARY, 1);
                LocalDate end = LocalDate.of(2020, Month.JANUARY, 31);
                LocalDateInterval interval = new LocalDateInterval(start, end);
                return new FrankfurterExchangeRateSetRequest(FOO_DOLLAR, Set.of(BAR_FRANC, BAZ_POUND), interval);
            },
            "https://api.frankfurter.app/2020-01-01..2020-01-31?from=FOO&to=BAR%2CBAZ",
            "https://api.frankfurter.app/2020-01-01..2020-01-31?to=BAR%2CBAZ&from=FOO"
    );
}
```

...where `FrankfurterExchangeRateSetRequest` is a deeply-immutable type, so "accidental" mutations are not possible.

There is a non-deterministic chance that the test will either pass flawlessly or throw an assertion error with a message that actually shows the `actual` value _is_ contained in `expected`:

```
java.lang.AssertionError: 
Expecting actual:
  https://api.frankfurter.app/2020-01-01..2020-01-31?from=FOO&to=BAZ%2CBAR
to be in:
  [https://api.frankfurter.app/2020-01-01..2020-01-31?from=FOO&to=BAR%2CBAZ,
    https://api.frankfurter.app/2020-01-01..2020-01-31?to=BAR%2CBAZ&from=FOO]
```

What's more, if `@Test` is to be replaced with `@RepeatedTest`, in the case of a failure _all_ repetitions fail, and in the case of success _all_ repetitions succeed.

**Comment by scordio** [comment]
`isIn` shouldn't really do anything special under the hood, aside from invoking `URI::equals`.

I was thinking that there might be URI fields to look at which are not shown in its `toString` but are still evaluated in `equals`. However, with a quick look at the Java 17 sources, I couldn't find any.

With a debugger, would you maybe have the chance to see which part of `URI::equals` is returning `false`?

**Comment by amodolo** [comment]
I think it's not a problem related to the AssertJ itself, but to the way you build the URI from the string chunks.
In fact you expected this URI
`https://api.frankfurter.app/2020-01-01..2020-01-31?from=FOO&to=BAZ%2CBAR`
to be contained in a connection that contains this one
`https://api.frankfurter.app/2020-01-01..2020-01-31?from=FOO&to=BAR%2CBAZ`
You can see that the to query param has different values. 

This because the Set collection (that you use to BAR_FRANC, BAZ_POUND values) doesn't guarantee the order

**Comment by northmaxdev** [comment]
Apologies for the delayed response.

@amodolo I think you are completely right! Which means this was my bad all along and the issue is not related to AssertJ after all.

Thanks to both of you for dedicating a few minutes either way.
