### ISSUE TITLE
Update pitest-maven-git license

### ISSUE THREAD

**Issue by etellman** [assertj/assertj#3140]
**Describe the bug**

The license for https://docs.arcmutate.com/docs/github/overview.html has expired, which means the `store-pitest-feedback` build target fails with a license error. See, for example https://github.com/assertj/assertj/actions/runs/5771789485/job/15646105757?pr=3126.

The expired license is here: https://github.com/assertj/assertj/blob/main/cdg-pitest-licence.txt

It looks like the license is free for open source projects and somebody just needs to email them to get it renewed:
https://subscribe.arcmutate.com/

I can follow up with them to get a new license, if nobody is already doing this.

**Comment by scordio** [comment]
Thanks for the heads up, @etellman! We're getting in touch with the Arcmutate team.
