### ISSUE TITLE
List comparator does not identify 2 Lists with different objects containing different value in JsonNode

### ISSUE THREAD

**Issue by ghughal** [assertj/assertj#3146]
**Describe the bug**
When using List to compare object that contains JsonNode object the comparison falsely validates 2 collection are same when they are not.

PS: this was noticed with JsonNode in our code but bug may not be related to that.

* assertj core version: 3.21.0
* java version: 11
* test framework version: JUnit 5.8.0
* Jackson version: 2.13.2
* lombok version: 1.18.12
* os (if relevant): N/A 

**Test case reproducing the bug**

Add a test case showing the bug that we can run

```java
    @Test
    @SneakyThrows
    void assertJBug() {
        final ObjectMapper objectMapper = new ObjectMapper();
        final List<Data> expected = List.of(new Data(objectMapper.readValue("{ \"some_key\": \"value\" }", JsonNode.class)));
        final List<Data> actual = List.of(new Data(objectMapper.readValue("{ \"some_other_key\": \"value\" }", JsonNode.class)));

        assertThat(actual)
            .usingRecursiveComparison()
            .ignoringCollectionOrder()
            .isNotEqualTo(expected); // expect this to pass but it failed
    }

    @Value
    public static class Data {
        private final JsonNode output;
    }
```

**Comment by scordio** [comment]
Just to make sure we analyze the right example, could you please provide the Delombok version of `Data`?

**Comment by JitendraProgrammer** [comment]
@ghughal 

Can i contribute here

**Comment by ghughal** [comment]
@JitendraProgrammer - yes, of course.

Here's de-lomboked version of code.

```java
    @Test
    void assertJBug() throws JsonProcessingException {
        final ObjectMapper objectMapper = new ObjectMapper();
        final List<Data> expected = List.of(new Data(objectMapper.readValue("{ \"some_key\": \"value\" }", JsonNode.class)));
        final List<Data> actual = List.of(new Data(objectMapper.readValue("{ \"some_other_key\": \"value\" }", JsonNode.class)));

        assertThat(actual)
            .usingRecursiveComparison()
            .ignoringCollectionOrder()
            .isNotEqualTo(expected); // expect this to pass but it fails
    }

    public static class Data {
        private final JsonNode output;

        public Data(final JsonNode output) {
            this.output = output;
        }

        public JsonNode getOutput() {
            return output;
        }

        @Override
        public boolean equals(final Object o) {
            if (this == o) return true;
            if (!(o instanceof Data)) return false;
            final Data other = (Data) o;
            return this.output.equals(other.output);
        }

        @Override
        public int hashCode() {
            return Objects.hash(getOutput());
        }

        @Override
        public String toString() {
            return new StringJoiner(", ", Data.class.getSimpleName() + "[", "]")
                .add("output=" + output)
                .toString();
        }
    }

**Comment by JitendraProgrammer** [comment]
Hi @ghughal,
Can you please try now

 @Test
    void assertJBug() throws JsonProcessingException {
        final ObjectMapper objectMapper = new ObjectMapper();
        final List<Data> expected = List.of(new Data(objectMapper.readValue("{ \"some_key\": \"value\" }", JsonNode.class)));
        final List<Data> actual = List.of(new Data(objectMapper.readValue("{ \"some_other_key\": \"value\" }", JsonNode.class)));

        Assertions.assertThat(actual)
            .usingRecursiveComparison()
            .ignoringCollectionOrder()
            .ignoringFields("output") // Ignore the 'output' field during comparison
            .isEqualTo(expected); // The assertion should now pass
    }

**Comment by ghughal** [comment]
@JitendraProgrammer - but I DO want to compare the output field. I'm comparing 2 List and want to make sure all fields matches.

**Comment by joel-costigliola** [comment]
@JitendraProgrammer thanks for wanting to contribute, the best way for this issue would to reproduce it and debug it to see if we have missed something indeed.

**Comment by joel-costigliola** [comment]
@ghughal the test succeeds as expected on the current commit, would you mind trying with a newer version and see if you still have the bug?
