### ISSUE TITLE
Error message for `containsSubsequence` is misleading for duplicate subsequence

### ISSUE THREAD

**Issue by sbrannen** [assertj/assertj#3159]
Version: AssertJ 3.24.2

Given the following assertion:

```java
assertThat("v1 : v2 : v3").containsSubsequence("v2", "v2", "v3");
```

The failure message is:

```
Expecting actual:
  "v1 : v2 : v3"
to contain the following CharSequences in this order:
  ["v2", "v2", "v3"]
but "v2" was found before "v2"
```

The `but "v2" was found before "v2"` message is misleading since the actual string does not contain two "v2" strings.

**Comment by joel-costigliola** [comment]
I agree it's misleading

**Comment by JohnBryte** [comment]
Hey @joel-costigliola @sbrannen 
Can I try to contribute to the project by solving this issue?
What error message would you suggest for this scenario?
Something like
```
Expecting actual:
  "v1 : v2 : v3"
to contain the following CharSequences in this order:
  ["v2", "v2", "v3"]
but second occurrence of "v2" was not found
```

**Comment by joel-costigliola** [comment]
@JohnBryte thanks, that would be appreciated.

Your suggestion works for me, I would also reword the sentence 
```
to contain the following CharSequences in this order:
```
to 
```
to contain the following CharSequences in this order (possibly with other values between them):
```
so that it is clear what we were trying to assert (a subsequence tolerates other values while a sequence is not)

**Comment by JohnBryte** [comment]
The issue has been resolved on my end. Would love to hear your thoughts and feedback whenever you have a moment. No rush.
Thank you

@joel-costigliola

**Comment by joel-costigliola** [comment]
Thanks, I'll have a look at it this weekend time permitting.

**Comment by sbrannen** [comment]
Should this be assigned to the 3.25.0 milestone?
