### ISSUE TITLE
org.opentest4j.AssertionFailedError

### ISSUE THREAD

**Issue by RedHoes** [assertj/assertj#3186]
**Describe the bug**
I met this error although I don't have any action_id fields in my code.
```
expected: "{"responseType":"ephemeral","blocks":[{"type":"section","text":{"type":"mrkdwn","text":":question: Hey <@1234> :wave: Click here for more details"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Show Help","emoji":false},"actionId":"button_click_action"}}]}"
 but was: "{"responseType":"ephemeral","blocks":[{"type":"section","text":{"type":"mrkdwn","text":":question: Hey <@1234> :wave: Click here for more details"},"accessory":{"type":"button","text":{"type":"plain_text","text":"Show Help","emoji":false},"action_id":"button_click_action"}}]}"
org.opentest4j.AssertionFailedError: 
```
* assertj core version: opentest4j
* java version: 11.0.20.1
* test framework version: 
* os (if relevant): 

**Test case reproducing the bug**

Add a test case showing the bug that we can run
![Screenshot from 2023-09-17 11-23-47](https://github.com/assertj/assertj/assets/95393817/080bf242-4e1a-4102-a125-60f3dc13d595)

**Comment by joel-costigliola** [comment]
@RedHoes can you provide us with a test case reproducing the bug ?
It's kinda impossible to help with that little information, we don't even know what assertion you were calling

**Comment by scordio** [comment]
Closing due to the lack of feedback. Happy to reopen the issue and look into it if a reproducible example can be provided.
