### ISSUE TITLE
`returns` and `doesNotReturn` should invoke `isNotNull` internally

### ISSUE THREAD

**Issue by mgrafl** [assertj/assertj#3222]
**Describe the bug**
The `AbstractObjectAssert#returns(...)` method should assert that the initial `actual` value is not `null`. Instead, it directly applies the `from` function, which then almost always throws a NullPointerException.

Compatibility consideration: 
While one could contrive a scenario where the `from` function can handle `null` values (e.g., `assertThat((Object)null).returns(true, from(java.util.Objects::isNull))`), I cannot think of a real-world use case where any further checks on a `null` `actual` value would provide any benefit.

* assertj core version: 3.24.2
* java version: 11
* test framework version: -
* os (if relevant): -

**Test case reproducing the bug**

The following code should throw an AssertionError instead of a NullPointerException.

```java
assertThat((Object)null).returns(null, from(Object::toString));
```

**Comment by scordio** [comment]
I agree we should guard `returns` and `doesNotReturn` with an `isNotNull` call.
