### ISSUE TITLE
limit depth of recursive comparison

### ISSUE THREAD

**Issue by jchambers-crescendo** [assertj/assertj#3227]
#### Feature summary

There appears to be no way currently to limit the depth of the recursive comparison, which I currently need for my use case.  I've been trying to implement it with `DefaultRecursiveComparisonIntrospectionStrategy`, but so far have had no luck.  Perhaps others would find this useful as well, figured I'd mention it here see if anyone has considered it.

#### Example

```java
assertThat(actual).usingRecursiveComparison(3);
```
or
```java
assertThat(actual).usingRecursiveComparison(new DepthAwareRecursiveComparisonConfiguration(3)
```

**Comment by scordio** [comment]
To understand better your use case, what would you expect when the limit is reached? A fallback to `equals` or just stop the comparison?

Would you have a concrete example to share?

**Comment by jchambers-crescendo** [comment]
I would like it to stop comparing once the given depth is reached.  My use case is that I have two POJOs which were generated by two different means and I want to compare them, but one of them is only populated to a given depth, so recursively comparing keeps failing.  I haven't yet managed to accomplish depth-aware recursive comparison myself.  I am trying to extend `RecursiveComparisonConfiguration`, but many of it's members are private and not available to subclasses.

**Comment by joel-costigliola** [comment]
Have you tried using [ignoringFieldsMatchingRegexes](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/RecursiveComparisonAssert.html#ignoringFieldsMatchingRegexes(java.lang.String...)) with some clever regexes that would match anything below a certain level ?

**Comment by joel-costigliola** [comment]
Happy it did!
