### ISSUE TITLE
Add `bytes()`/`bytes(Charset)`/`bytes(String)` navigation methods to `AbstractStringAssert`

### ISSUE THREAD

**Issue by onacit** [assertj/assertj#3229]
#### Feature summary

Add `AbstractStirngAssert#extracting(Charset)AbstractByteArrayAssert` so that the `byte[]` can be verified.

#### Example

```java
String actual  = "";
assertThat(actual)
        .hasSize(0)
        .extracting(StandardCharset.US_ASCII) // AbstractByteArrayAssert
        .hasSize(0)
;
```

**Comment by scordio** [comment]
What if we would stay closer to [`getBytes(Charset)`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/String.html#getBytes(java.nio.charset.Charset))?

Following the style of other navigation methods, we could add `bytes(Charset)`:

```java
String actual  = "";
assertThat(actual)
        .hasSize(0)
        .bytes(StandardCharset.US_ASCII) // AbstractByteArrayAssert
        .hasSize(0)
```

I would also consider the variant without parameters and the one with `String`.

**Comment by onacit** [comment]
@scordio The `bytes(Charset)` seems nice. Thank you.

**Comment by etrandafir93** [comment]
@scordio I was looking into this one as it seems like a good starting point. 

I've noticed that there are already methods such as `AbstractStringAssert::asByte` and `AbstractByteArrayAssert::asString` and `AbstractByteArrayAssert::asString(Charset)`.  What do you think about using the "**as**" prefix for consistency? so basically _asBytes()_ and _asByts(Charset)_

**Comment by scordio** [comment]
Thanks for your interest, @etrandafir93!

> I've noticed that there are already methods such as `AbstractStringAssert::asByte` and `AbstractByteArrayAssert::asString` and `AbstractByteArrayAssert::asString(Charset)`. What do you think about using the "**as**" prefix for consistency? so basically _asBytes()_ , _asBytes(Charset)_ and _asBytes(String)_

To the best of my knowledge, there is no `asByte` in `AbstractStringAssert` but we do have other methods like `asBase64Decoded`.

We tend to favor the `as` prefix for methods that perform additional transformations under the hood, while we prefer not to use any prefix when we delegate the execution to an API provided by the underlying type. An example is [`AbstractThrowableAssert::cause`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractThrowableAssert.html#cause()) that delegates to [`Throwable::getCause`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Throwable.html#getCause()).

For this reason, I would go with `bytes` for this case.

> Lastly, what do you think the expected behavior should be in case of a null (actual) String? Should It throw an exception right away? or return a _ByteArrayAssert_ with a _null_ actual value? There are a few examples in the PR link

It doesn't make much sense to execute navigation methods when the object under test is null, therefore I suggest performing an [`isNotNull()`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/Assert.html#isNotNull()) call internally before creating the new assertion object.

**Comment by etrandafir93** [comment]
@scordio this is the [asByte()](https://github.com/assertj/assertj/blob/0eb44cc99f1d0e106e2335d0b1e851a85bf73466/assertj-core/src/main/java/org/assertj/core/api/AbstractStringAssert.java#L454) method i was referring to. I have now applied the suggestions and fixed the formatting issues.

**Comment by scordio** [comment]
Right, I was mistakenly looking at the released version instead of the latest codebase, sorry 🙂

**Comment by etrandafir93** [comment]
Hello @scordio, @joel-costigliola,

I've opened the [https://github.com/assertj/assertj/pull/3232](https://github.com/assertj/assertj/pull/3232) some time ago.  I'd appreciate your feedback here whenever you have a moment - your time and expertise in reviewing this would mean a lot. 

Let me know if there's anything I can do to assist in the process. Thanks, and I'm looking forward to your response.

**Comment by scordio** [comment]
Hi @etrandafir93 , thanks a lot and apologies for the delay.

We're currently finalizing 3.25.0 and we'll need some time before we can jump on your PR.

As we want to freeze the release scope, I'll schedule your changes for 3.26.0.

**Comment by etrandafir93** [comment]
No worries, thanks for reaching out and explaining the process!

**Comment by joel-costigliola** [comment]
Closed by https://github.com/assertj/assertj/pull/3232
