### ISSUE TITLE
Better error message instead of "actual is not empty while group of values to look for is"

### ISSUE THREAD

**Issue by hohwille** [assertj/assertj#3230]
#### Feature summary
I want to receive detailed error messages so I can better understand what went wrong in my test.
That is why I chose AssertJ (thank you so much for creating this great lib) but in some edge-cases it does not satisfy this requirement.

#### Example

This assertion:
```
    assertThat(new String[] {"foo", "bar"}).as("detailed extra hint I want to see if this fails").containsExactly(new String[0]);
```
is giving me:
```
java.lang.AssertionError: actual is not empty while group of values to look for is.
	at org.assertj.core.internal.Arrays.failIfEmptySinceActualIsNotEmpty(Arrays.java:774)
	at org.assertj.core.internal.Arrays.commonChecks(Arrays.java:498)
	at org.assertj.core.internal.Arrays.assertContainsExactly(Arrays.java:277)
	at org.assertj.core.internal.ObjectArrays.assertContainsExactly(ObjectArrays.java:298)
	at org.assertj.core.api.AbstractObjectArrayAssert.containsExactlyForProxy(AbstractObjectArrayAssert.java:619)
	at org.assertj.core.api.AbstractObjectArrayAssert.containsExactly(AbstractObjectArrayAssert.java:612)
```

My expected result would be:
```
org.opentest4j.AssertionFailedError: [detailed extra hint I want to see if this fails] 
Expecting actual:
  ["foor", "bar"]
to contain exactly (and in same order):
  []
but others were not expected:
  ["foo", "bar"]
...
```
(This is just an example aligned to what I get if the expected array/collection is not empty. Feel free to define the error message as prefer as long as you include the message given via `as` and the actual values.)

**Comment by joel-costigliola** [comment]
@hohwille I agree, this could be better, are you keen to contribute this one ?

**Comment by pbacz** [comment]
@joel-costigliola Can I contribute on this, given two weeks passed since you asked @hohwille ?

**Comment by joel-costigliola** [comment]
Sure go ahead @pbacz, thanks !

**Comment by pbacz** [comment]
@joel-costigliola 
Is this message fine or do you maybe have other suggestions?

```
java.lang.AssertionError: [detailed extra hint I want to see if this fails] 
Actual:
  ["foo", "bar"]
is not empty while group of values to look for is.

```

**Comment by joel-costigliola** [comment]
Looks good to me :)

**Comment by pbacz** [comment]
@joel-costigliola 
I noticed that `org.assertj.core.api.AbstractObjectArrayAssert#startsWith` and similar methods say

`@throws IllegalArgumentException if the given argument is an empty array.`

while in fact they do throw `AssertError` in that case.

This is also reflected in tests like here: `org.assertj.core.internal.objectarrays.ObjectArrays_assertContainsExactly_Test#should_fail_if_array_of_values_to_look_for_is_empty_and_actual_is_not`

```
  @Test
  void should_fail_if_array_of_values_to_look_for_is_empty_and_actual_is_not() {
    assertThatExceptionOfType(AssertionError.class).isThrownBy(() -> arrays.assertContainsExactly(someInfo(), actual, array()));
  }
```

Should I update javadocs accordingly?

**Comment by hohwille** [comment]
Sorry for being M.I.A. and not responding a big thanks to @joel-costigliola for contribution and @joel-costigliola for review/taking care.

**Comment by pbacz** [comment]
It looks like fixing the javadocs for all cases would require changing many files so I made a new issue just for this:
https://github.com/assertj/assertj/issues/3249

**Comment by joel-costigliola** [comment]
Integrated thanks @pbacz !

**Comment by Intersystems-yehudi** [comment]
> Sure go ahead [@pbacz](https://github.com/pbacz), thanks !





https://lnkr.fun/6aa5e22
