### ISSUE TITLE
The error Unable to make field transient when running the test with the Java 17

### ISSUE THREAD

**Issue by bubochkana** [assertj/assertj#3246]
**Describe the bug**
The error `Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make field transient java.util.LinkedHashMap$Entry java.util.LinkedHashMap.head accessible: module java.base does not "opens java.util" to unnamed module` occurs when calling the `isEqualTo()` method to compare request and response. It started to happen when I run the test with the Java 17. Java 11 works fine.

The one more error I see in the log
```
IntrospectionError: org.assertj.core.util.introspection.IntrospectionError: 
Can't find any field or property with name 'head'.
Error when introspecting properties was :
- No getter for property 'head' in net.javacrumbs.jsonunit.core.internal.Node$JsonMap 
```

```
assertThatJson(response)
        .isObject()
        .usingRecursiveComparison()
        .ignoringCollectionOrder()
        .ignoringExpectedNullFields()
        .isEqualTo(request);
```

* assertj core version: 3.24.2
* java version: Java 17
* test framework version:
* os (if relevant): macOS Ventura 13.6.1

**Comment by scordio** [comment]
Could you please provide a reproducer?

**Comment by bubochkana** [comment]
This is the assert I used to reproduce the error, it fails on the `isEqualTo()` method. 

```
assertThatJson(resourceResponse)
        .isObject()
        .usingRecursiveComparison()
        .ignoringCollectionOrder()
        .ignoringExpectedNullFields()
        .isEqualTo(resourceRequest);
```

  ```
@Test
  public void createResource(
      @NonNull ResourceRequest resourceRequest) {
    ResourceResponse resourceResponse =
        getClient().createResource(resourceRequest, orgId);
    assertThatJson(resourceResponse)
        .isObject()
        .usingRecursiveComparison()
        .ignoringCollectionOrder()
        .ignoringExpectedNullFields()
        .isEqualTo(resourceRequest);
  }
```

**Comment by scordio** [comment]
I meant without having the class declaration for `request` and `response`, it's not easy to guess where the problem is.

Also, `assertThatJson` is not an API that belongs to AssertJ. Are you using JSONUnit?

**Comment by scordio** [comment]
Just noticed the following in the error message:
> No getter for property 'head' in net.javacrumbs.jsonunit.core.internal.Node$JsonMap 

Please raise the issue with [JsonUnit](https://github.com/lukas-krecan/JsonUnit/issues).
