### ISSUE TITLE
Suggesting a doesNotThrowAnyExceptionExcept(...) method

### ISSUE THREAD

**Issue by pandoras-toolbox** [assertj/assertj#3248]
#### Feature summary

As discussed in [another issue](https://github.com/assertj/assertj/issues/2517#issuecomment-1788856623), here is the suggestion to support being able to ignore certain exceptions when not expecting exceptions.

It would be similar to what can be done with the [Selenium API](https://www.selenium.dev/selenium/docs/api/java/org/openqa/selenium/support/ui/FluentWait.html):

```java
   // Waiting 30 seconds for an element to be present on the page, checking
   // for its presence once every 5 seconds.
   Wait<WebDriver> wait = new FluentWait<WebDriver>(driver)
       .withTimeout(Duration.ofSeconds(30L))
       .pollingEvery(Duration.ofSeconds(5L))
       .ignoring(NoSuchElementException.class);
```

#### Example

That is how it can look in AssertJ:

```java
assertThatCode(() -> { thisFunctionDoesNothing(); })
                .doesNotThrowAnyExceptionExcept(NoSuchElementException.class, IOException.class);
```

**Comment by pbacz** [comment]
Is this one free for taking?

**Comment by pbacz** [comment]
@joel-costigliola Is this one free for taking?

**Comment by joel-costigliola** [comment]
It is @pbacz :wink:

**Comment by pbacz** [comment]
@joel-costigliola
Great 👍🏻
I'd like to contribute. 
Before I begin I'd like to clarify. When `doesNotThrowAnyExceptionExcept(IOException.class) is called and a subclass of IOException is thrown, then the case should pass, shouldn't it.
