### ISSUE TITLE
Wrong javadoc in AbstractObjectArrayAssert (and similar)

### ISSUE THREAD

**Issue by pbacz** [assertj/assertj#3249]
I noticed that currently `org.assertj.core.api.AbstractObjectArrayAssert#startsWith` and similar methods in this and other array related classes say

`@throws IllegalArgumentException if the given argument is an empty array.`

while in fact they do throw `AssertError` in that case (and only if the actual is not empty, the check pass if both arrays passed are empty).

This is also reflected in tests like here: `org.assertj.core.internal.objectarrays.ObjectArrays_assertContainsExactly_Test#should_fail_if_array_of_values_to_look_for_is_empty_and_actual_is_not`

```
  @Test
  void should_fail_if_array_of_values_to_look_for_is_empty_and_actual_is_not() {
    assertThatExceptionOfType(AssertionError.class).isThrownBy(() -> arrays.assertContainsExactly(someInfo(), actual, array()));
  }
```

It would be great to fix the javadoc. I can contribute to this.

**Comment by joel-costigliola** [comment]
Good catch, please send us a PR, thanks @pbacz !

**Comment by joel-costigliola** [comment]
done in https://github.com/assertj/assertj/commit/87f454ec22719baae69eec0b6f7cd826f70e8fde
