### ISSUE TITLE
Support ability to inspect the return value of an expression after checking no exception is raised.

### ISSUE THREAD

**Issue by ascopes** [assertj/assertj#3262]
#### Feature summary

I have a use case where I want to be able to verify no exception is raised by a method call, and then proceed to perform assertions on the return value.

Due to how AssertJ works, I currently would need to either nest assertions in themselves, which breaks the flow of the test up and makes it harder to read, or I'd need to perform the method call twice, which risks missing accidental side effects that may occur on specific invocations.

Currently:

```java
assertThatNoException()
    .isThrownBy(() -> {
      var result = getFileSystems(exclusions);
      // assertions here.
    });
```
or
```java
assertThatNoException()
    .isThrownBy(() -> getFileSystems(exclusions));
assertThat(getFileSystems(exclusions))
    .containsExactly(fileSystem1, fileSystem2);
```

My proposal is to add the ability to inspect the return value of method calls after asserting that they do not throw anything.

This could look something like one of the following:

```java
assertThatCode(() -> getFileSystems(exclusions))
    .doesNotThrowException()
    .andReturnValue()
    .containsExactly(fileSystem1, fileSystem2);

```java
assertThatNoException()
    .isThrownBy(() -> getFileSystems(exclusions))
    .andReturnValue()
    .containsExactly(fileSystem1, fileSystem2);
```

I believe this could be supported by modifying `ThrowableAssert` to support a second functional interface type that has a provided return value. If that overload is used, then the result could be stored in the ThrowableAssert and retrieved when performing further assertions.

**Comment by scordio** [comment]
If I'm not mistaken, this seems to be a duplicate of #1652.

Because of that one, I drafted #2519. Let me know if my proposal would be a good fit for your use case 🙂

**Comment by ascopes** [comment]
@scordio will take a look, thanks! I think this is exactly what I'd need.

**Comment by ascopes** [comment]
Dupe of #1652 that is covered by #2519
