### ISSUE TITLE
`hasPermittedSubclasses` and `hasNoPermittedSubclasses` for `Class` assertions

### ISSUE THREAD

**Issue by scordio** [assertj/assertj#3263]
We should add `hasPermittedSubclasses(Class<?>...)` and `hasNoPermittedSubclasses()` to `Class` assertions, following [`Class::getPermittedSubclasses`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Class.html#getPermittedSubclasses()).

As we still target Java 8, the implementation should be reflection-based, similar to #3080.

**Comment by pbacz** [comment]
@scordio Can I contribute to this one?

**Comment by scordio** [comment]
Sure and thanks, @pbacz!

**Comment by pbacz** [comment]
@scordio 
After conducting an initial investigation, I have identified a concern regarding this idea. From a Java perspective, it is impossible to create a sealed class without any permitted subclasses. This limitation could render the proposed assertion method useless.
However, it's noteworthy that both the class file specification and the Javadoc for Class::getPermittedSubclasses suggest that such a scenario is possible.

In light of this, I would like to seek your input on the following questions:
- Should we proceed with adding this assertion despite the aforementioned Java constraint?
- If the decision is affirmative, be advised that crafting a test for this scenario may involve unconventional methods to load a sealed class without any permitted subclasses (potentially by adding a prepared class file to the repository and loading it using a custom class loader). Are you comfortable with employing such strategies in the testing process?

**Comment by scordio** [comment]
You're referring to `hasNoPermittedSubclasses()`, right? (I just edited the description to show the expected parameters for the two methods)

> From a Java perspective, it is impossible to create a sealed class without any permitted subclasses. This limitation could render the proposed assertion method useless.

That's absolutely correct when the object under test is a sealed class. However, `hasNoPermittedSubclasses()` should work properly with the cases mentioned in the `getPermittedSubclasses` Javadoc:

> If this Class object represents a primitive type, `void`, an array type, or a class or interface that is not sealed, that is [`isSealed()`](https://docs.oracle.com/en/java/javase/21/docs/api/java.base/java/lang/Class.html#isSealed()) returns `false`, then this method returns `null`.

We might have a testing strategy similar to [how we tested `hasNoSuperclass`](https://github.com/assertj/assertj/blob/8ec30c71d4e2a27f362546750ff874a04f9923de/assertj-core/src/test/java/org/assertj/core/api/classes/ClassAssert_hasNoSuperclass_Test.java#L56C58-L68).

Would that make sense?

**Comment by scordio** [comment]
@pbacz I propose we add only `hasPermittedSubclasses` with `contains` behavior and we can always add more if there is a concrete demand.

WDYT?

**Comment by pbacz** [comment]
@scordio I think it's fine. I'll do it this way.

**Comment by pbacz** [comment]
@scordio 
Hi, a PR is ready.
