### ISSUE TITLE
Please release with a Java 21-compatible ByteBuddy

### ISSUE THREAD

**Issue by ogregoire** [assertj/assertj#3280]
**Describe the bug**
Using Gradle, the latest released version of AssertJ requires a version of ByteBuddy that is incompatible with Java 21. Both Mockito 5.7.0 and AssertJ 3.24.2 use ByteBuddy and somehow the version of ByteBuddy is picked up from AssertJ's dependencies, not Mockito's. Mockito then fails because the version of ByteBuddy being picked up is not its own dependency.

Manually declaring a dependency to the latest version of ByteBuddy fixes the issue, but it shouldn't be the case for an important version such as 21. So please either release 3.25.0 if it's ready or 3.24.3 with just your dependency of ByteBuddy bumped to a Java 21-compatible version if all tests pass.

* assertj core version: 3.24.2
* java version: JDK 21 with Mockito 5.7.0
* test framework version: 
* os (if relevant):

**Comment by scordio** [comment]
3.25.0 will be released soon. Meanwhile, as you mentioned, the workaround is to declare ByteBuddy explicitly.
