### ISSUE TITLE
Add `values()` navigation method to `AbstractMapAssert`

### ISSUE THREAD

**Issue by xenoterracide** [assertj/assertj#3291]
#### Feature summary

Improve matching only MapAssert Value Properties.

#### Example

I feel like this could be one statement

```java
assertThat(cpCard.getAltIds())
  .as("AlternateId saved on card")
  .hasSize(1); // avoids getAltIds() possible NPE... 

assertThat(cpCard.getAltIds().values())
  .as("AlternateId saved on Card")
  .first()
  .returns(LoyaltyCardsValueAltIdsValue.StatusEnum.ACTIVE, LoyaltyCardsValueAltIdsValue::getStatus);
```

It feels like I should be able to do something like. I tried a number of `extracting` but it all ended up more convoluted than 2 statements, or required a weaker static typing

```java
assertThat(cpCard.getAltIds())
  .hasSize(1)
  .values()
  .first()
  .returns(...);
```

**Comment by scordio** [comment]
I slightly modified the formatting of your code snippets to better visualize each method call.

If I understand it correctly, the second snippet contains what you'd like to have.

With `values`, the following could be written:

```java
assertThat(cpCard.getAltIds())
  .values() // returns AbstractCollectionAssert after calling Map::values
  .singleElement()
  .returns(...);
```

Would that satisfy your use case?

**Comment by xenoterracide** [comment]
in this particular case sure. I just grabbed `first()` from the existing chain. I'm not certain though that there isn't another case that wouldn't need more. I guess it made sense to me that after grabbing values I'd be in the same context as the thing that works and so the API would be the same.

**Comment by scordio** [comment]
Ok, so let's add `values` as a start and see if any other concrete use cases arise.
