### ISSUE TITLE
Add `onProperty` method that works like `extracting` but without changing original assertion type

### ISSUE THREAD

**Issue by Kruschenstein** [assertj/assertj#3307]
#### Feature summary

I really like the  `extracting` methods, but it's always disappointing that when the method is called, we cannot go back to the original object. I think, we could easily fix this issue by providing a new kind of "extracting" method which take an extractor and another `Consumer`. The parameter of the consumer would be an `assert` setup with the extracted element. See following example:

#### Example

```java
record Character(String name, int age) {}

var john = new Character("John", 12);
assertThat(john)
    .onProperty(Character::name, it -> it.startsWith("Jo").endsWith("hn"))
    .onProperty(Character::age, it -> it.isGreaterThan(10).isLowerThan(32));
```

Here I named this new method `onPorperty` to try to keep the "semantic" API : "assert that character on property name, it starts with ...". I'm not a native english speaker, and maybe we could find a better method name ^^'.

I focus on `onProperty` method that take a `Supplier` as first argument, because I imagine that it's more simple to implement and to use. But it could be nice to have the same behavior as existing `extracting` with the property name given as first argument and a factory as second.

I would be happy to contribute and add this feature to assertJ. So if you are ok, let me know :smiley: !

**Comment by joel-costigliola** [comment]
I'm not saying this is as good but you can alreay do a similar thing with [satisfies](https://www.javadoc.io/static/org.assertj/assertj-core/3.24.2/org/assertj/core/api/AbstractAssert.html#satisfies(java.util.function.Consumer...)) 

```java
 // second constructor parameter is the light saber color
 Jedi yoda = new Jedi("Yoda", "Green");
 Jedi luke = new Jedi("Luke Skywalker", "Green");

 Consumer<Jedi> redLightSaber = jedi -> assertThat(jedi.getLightSaberColor()).isEqualTo("Red");
 Consumer<Jedi> greenLightSaber = jedi -> assertThat(jedi.getLightSaberColor()).isEqualTo("Green");
 Consumer<Jedi> notDarth = jedi -> assertThat(jedi.getName()).doesNotContain("Darth");
 Consumer<Jedi> darth = jedi -> assertThat(jedi.getName()).contains("Darth");

 // assertions succeed:
 assertThat(yoda).satisfies(greenLightSaber);
 assertThat(luke).satisfies(greenLightSaber, notDarth);

 // assertions fail:
 Jedi vader = new Jedi("Darth Vader", "Red");
 assertThat(vader).satisfies(greenLightSaber);
 assertThat(vader).satisfies(darth, greenLightSaber);
 assertThat(vader).satisfies(greenLightSaber, notDarth);
```

**Comment by scordio** [comment]
> I think, we could easily fix this issue by providing a new kind of "extracting" method which take an extractor and another `Consumer`. The parameter of the consumer would be an `assert` setup with the extracted element.

That won't work, unfortunately, similar to how [`extracting(Function)`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractObjectAssert.html#extracting(java.util.function.Function)) cannot provide type-specific assertions.

Your example uses type-specific assertions:

```java
assertThat(john)
    .onProperty(Character::name, it -> it.startsWith("Jo").endsWith("hn")) // `it` must be an `AbstractStringAssert` instance
    .onProperty(Character::age, it -> it.isGreaterThan(10).isLowerThan(32)); // `it` must be an `AbstractIntegerAssert` instance
``` 

However, there isn't enough information for the compiler to infer that the `String` value from `Character::name` should be "mapped" to a `StringAssert` instance, or that the `int` value from `Character::age` should be mapped to an `IntegerAssert` instance.

That's exactly the challenge that [`asInstanceOf`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/Assert.html#asInstanceOf(org.assertj.core.api.InstanceOfAssertFactory)) together with [`InstanceOfAssertFactories`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/InstanceOfAssertFactories.html) tries to solve.

The [`extracting(Function, InstanceOfAssertFactory)`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractObjectAssert.html#extracting(java.util.function.Function,org.assertj.core.api.InstanceOfAssertFactory)) variant also helps with such extracting-related use cases.

**Comment by Kruschenstein** [comment]
Indeed, I test on my own side, and have something that works (that's why I posted here previously). Let me show :

In `AbstractObjectAssert`:
```java
  @FunctionalInterface
  public interface StringProducerFunction<T> extends Function<T, String> {}
  @FunctionalInterface
  public interface CollectionProducerFunction<T, E> extends Function<T, Collection<E>> {}

  public SELF onProperty(StringProducerFunction<ACTUAL> extractor, Consumer<StringAssert> consumer) {
    consumer.accept(new StringAssert(extractor.apply(actual)));
    return myself;
  }

  public <T> SELF onProperty(CollectionProducerFunction<ACTUAL, T> extractor, Consumer<CollectionAssert<T>> consumer) {
    consumer.accept(new CollectionAssert<>(extractor.apply(actual)));
    return myself;
  }
```

So if I write a test:
```java
  record Foo(String foo, List<String> bar) {}

  @Test
  void should_succeed() {
    Foo foo = new Foo("foo", Jdk11.List.of("foo", "bar", "baz"));

    assertThat(foo)
      .onProperty(Foo::foo, it -> it.startsWith("f"))
      .onProperty(Foo::bar, it -> it.contains("foo"));
  }
```

That works pretty well. For sure, I know about Java generics type erasure, so I tried to fool the java compiler by fixing generic types with "more concrete" interface. So it forces me to write a lot of interface, but I think it's the library work to write "not fun" code to let users have fun! Thus with this I'm able to write the code above. And everything looks fine. Until...

```java
  @Test
  void should_succeed() {
    Foo foo = new Foo("foo", Jdk11.List.of("foo", "bar", "baz"));

    assertThat(foo)
      .onProperty(f -> f.foo(), it -> it.startsWith("f"))
      .onProperty(f -> f.bar(), it -> it.contains("foo"));
  }
```
If I use lambda instead of method reference, the compiler says it cannot infer types. I'm working with Java everyday, and I'm always surprised when I have this kind of strange behavior with generics.

So I realize that my purpose is impossible to implements with a coherent behavior. That's disappointing  as the generics type erasure in Java is, but as we say in France "c'est la vie"!

I'll try to satisfy myself with `satifsies` :thinking: :sunglasses: 

Thanks for your time and have a nice day :smile:
