### ISSUE TITLE
Compile error due to new assertThatThrownBy

### ISSUE THREAD

**Issue by Bananeweizen** [assertj/assertj#3314]
**Describe the bug**
Compile error in Eclipse 2023-12: The method assertThatThrownBy(ThrowableAssert.ThrowingCallable) is ambiguous for the type AmbigiousCallTest.

The only change is the upgrade from 3.24.2 to 3.25. In 3.24.2 the same code was fine.

* assertj core version: 3.25

**Test case reproducing the bug**

Don't *run* the below code, but just *compile* it. At least ECJ doesn't like it.

```java
public class AmbigiousCallTest {

    @Test
    void ambigiousCall() throws Exception {
        assertThatThrownBy(AmbigiousCallTest::verify)
                .hasMessageContaining("No objects are given");
    }

    public static void verify(final Object... objects) {
        // foo
    }

}
```

Probably related to #3043. Workaround: Extract the method reference to a local variable. The type information of that local variable is sufficient to choose one of the two methods.

**Comment by scordio** [comment]
Thanks for reporting it, @Bananeweizen.

We're in discussion with the team if we should revert cf06398587da23ac530b03a941e0efe6cf29aef7 as it introduced a breaking change we didn't spot before.

**Comment by asolntsev** [comment]
My code also doesn't compile after upgrading to AssertJ 3.25.0,
BUT

@scordio I would like to mention that this is not a big deal for me. 
I just need to replace method reference (which is not really convenient to read):
```java
assertThatThrownBy(Selenide::confirm)
      .isInstanceOf(AlertNotFoundError.class)
```

to a "standard" lambda (which is better readable to me):
```java
assertThatThrownBy(() -> Selenide.confirm())
      .isInstanceOf(AlertNotFoundError.class)
```

**Comment by sbrannen** [comment]
We got hit by this in Spring Framework as well.

https://github.com/spring-projects/spring-framework/commit/ffddbb586e60ce1b66a3b962612636db9c61ed81#diff-58b8a6574dcffc60614d0727c28b36039f5bc28a04143486722d908a24ff55c7

**Comment by sbrannen** [comment]
FWIW, if you do intend to keep `ThrowingCallableWithValue`, note that most people typically call that a `ThrowingSupplier`. 😉

**Comment by scordio** [comment]
**Team decision**: cf06398587da23ac530b03a941e0efe6cf29aef7 should be reverted and #3043 should be evaluated again together with #1652 / #2519.

**Comment by chadlwilson** [comment]
While the workaround isn't so bad with Java, it seemed a little more painful with Groovy, so appreciate the revert for now.

(**disclaimer**: not a Groovy expert so correction is fine if there is a more elegant way to do this ... short of falling back to Java-style syntax!)

```groovy
assertThatThrownBy { doThing() }
```
became
```groovy
assertThatThrownBy({ doThing() } as ThrowableAssert.ThrowingCallableWithValue)
```

**Comment by ascopes** [comment]
Is it worth adding test cases to catch this in the future?

**Comment by scordio** [comment]
@ascopes already done, see #3318.

**Comment by ascopes** [comment]
great, thanks for the quick fixes!

**Comment by Bananeweizen** [comment]
@scordio This is a bit out of scope, but could you imagine to build and test some other popular projects with every commit to master, using the freshly compiled assertj version? Similar to how the OpenJDK quality outreach program builds and tests 30(?) popular Java libraries regularly with their HEAD revision of Java, to verify they still work fine. That way regressions could be found soon after they are introduced, independent of a release.

**Comment by scordio** [comment]
That's an interesting idea, @Bananeweizen!

We're involved in the quality outreach program but I wasn't aware that OpenJDK is pulling & building projects. Until now, we provided manual feedback on which versions we test against.

Would you have any references about it?

Anyway, it's worth investigating how to do it for some projects like Spring and JUnit. We'll discuss it with the team.

Thanks again for bringing this up!

**Comment by ascopes** [comment]
Agree this sounds like a useful idea.

As an example, the library I referenced above flagged this issue, so could be a candidate for this sort of thing potentially.
