### ISSUE TITLE
AssertJ cannot compare arrays in maps

### ISSUE THREAD

**Issue by asolntsev** [assertj/assertj#3315]
**Describe the bug**

* assertj core version: 3.25.0
* java version: 17
* test framework version: JUnit 5.10.1
* os (if relevant): MacOS Sonoma 14.2.1

**Test case reproducing the bug**

This code worked in AssertJ 3.24.2, but fails in AssertJ 3.25.0:

```java
import static org.assertj.core.api.Assertions.assertThat;
import org.junit.jupiter.api.Test;
import java.util.Map;

  @Test
  void fails() {
    assertThat(Map.of("firstName", new String[] {"Bob"}))
      .containsExactlyEntriesOf(Map.of("firstName", new String[] {"Bob"}));
  }
```

This test fails with the error message:
```java
    java.lang.AssertionError: 
    Actual and expected have the same elements but not in the same order, at index 0 actual element was:
      "firstName"=["Bob"]
    whereas expected element was:
      "firstName"=["Bob"]
        at play.utils.UtilsTest.fails(UtilsTest.java:50)
```

**Comment by scordio** [comment]
Thanks for reporting it, @asolntsev!

**Comment by scordio** [comment]
The change that causes the issue is 98d3eaad2899256c09731d98dc04f7f66bd8c151.

**Comment by scordio** [comment]
Here we assume that the map value can be compared with `equals`:

https://github.com/assertj/assertj/blob/25347d57bb28295548ec6bd5b06e70b6d03496c9/assertj-core/src/main/java/org/assertj/core/internal/Maps.java#L572

This cannot work with array values as `equals` compares identity and not the array's content.

**Comment by scordio** [comment]
**Team decision**: 498ee5bb0a5cc367420cdb3c8e0e93d6e4bf5e51 should be reverted and #2165 should be addressed again with the knowledge gathered from this issue.
