### ISSUE TITLE
Regression in `AbstractMapAssert.containsExactly` causes `NullPointerException`

### ISSUE THREAD

**Issue by sbrannen** [assertj/assertj#3317]
**Describe the bug**

* assertj core version: 3.25.0

Commit 498ee5bb0a5cc367420cdb3c8e0e93d6e4bf5e51 introduced a regression in `AbstractMapAssert.containsExactly`.

Specifically, it is not always safe to put `null` into a `Map`.

https://github.com/assertj/assertj/blob/887f97b65da068e03308a6373a0c8a76912377aa/assertj-core/src/main/java/org/assertj/core/internal/Maps.java#L589

**Test case reproducing the bug**

The following now fails with a `NullPointerException`.

```java
@Test
void assertJBug() {
	Properties properties = new Properties();
	properties.setProperty("k1", "v1");
	properties.setProperty("k2", "v2");
	assertThat(properties).containsExactly(entry("k1", "v1"), entry("k2", "v2"));
}
```

**Comment by scordio** [comment]
Thanks for reporting it and the analysis, @sbrannen!

**Comment by sbrannen** [comment]
In case anyone else runs into this, you may find the workaround I came up with suitable for your use case as well.

https://github.com/spring-projects/spring-framework/commit/ffddbb586e60ce1b66a3b962612636db9c61ed81#diff-6f347f5b75cdbb58d65e5ec32c8e3ffe9abf719f50f3bc819ec257296d466aee

Basically, I created a new map (`LinkedHashMap` in this case) based on the original map (`Properties` in this case), and the `NullPointerException` is avoided since `LinkedHashMap` supports `null` values.

**Comment by scordio** [comment]
**Team decision**: 498ee5bb0a5cc367420cdb3c8e0e93d6e4bf5e51 should be reverted and #2165 should be addressed again with the knowledge gathered from this issue.

**Comment by sbrannen** [comment]
Thanks for the quick turnaround! 👍
