### ISSUE TITLE
Improve interoperability of `asInstanceOf` with `Set` instances

### ISSUE THREAD

**Issue by scordio** [assertj/assertj#3322]
Right now, there is no nice way to call `asInstanceOf` when a `Set` instance is expected.

Current solutions:

```java
Object actual = Set.of("first", "second");

assertThat(actual)
  .asInstanceOf(InstanceOfAssertFactories.type(Set.class))
  .satisfies(set -> assertThat(set).containsExactly("first", "second")); // unchecked warning

assertThat(actual)
  .asInstanceOf(InstanceOfAssertFactories.COLLECTION) // no implicit `isInstanceOf(Set.class)`
  .containsExactly("first", "second"));

assertThat(map.get("value"))
  .asInstanceOf(new InstanceOfAssertFactory<>(Set.class, Assertions::<String> assertThat)) // verbose
  .containsExactly("first", "second");
```

By design, we didn't introduce any `InstanceOfAssertFactory` for types that don't have more specific assertions, i.e., there is no `AbstractSetAssert` today because it wouldn't have any added value compared to [`AbstractCollectionAssert`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractCollectionAssert.html).

We should investigate how to improve such use cases.

Triggered by: https://github.com/spring-projects/spring-framework/blob/2784f6008e97c7283b2e57e98d18a89fe8f530ae/spring-beans/src/test/java/org/springframework/beans/factory/config/YamlProcessorTests.java#L144-L153

**Comment by sbrannen** [comment]
This works quite nicely! 👍 

See: https://github.com/spring-projects/spring-framework/commit/8feb842df5c55cb5c319cc7cea6af10394c0ce10

**Comment by scordio** [comment]
Nice! Thanks for the feedback!
