### ISSUE TITLE
`isNotEqualTo(boolean)` fails if `actual` is null

### ISSUE THREAD

**Issue by biergit** [assertj/assertj#3341]
`assertThat(Boolean.TRUE).isEqualTo(true)` -> success
`assertThat((Boolean)null).isNotEqualTo(Boolean.TRUE)` -> success
`assertThat((Boolean)null).isNotEqualTo(true)` -> Expecting actual not to be null.

**Comment by scordio** [comment]
It seems so 😉 

```java
assertThat(Boolean.TRUE.equals(true)).isTrue(); // succeeds
```

**Comment by biergit** [comment]
Hi @scordio, sure I'll take a look :)
