### ISSUE TITLE
Suggesting "hasOnlyDuplicates()" assertion

### ISSUE THREAD

**Issue by pandoras-toolbox** [assertj/assertj#3342]
What about adding an assertion to AssertJ for checking that a collection contains only duplicates?

There is an assertion for the opposite: `doesNotHaveDuplicates()`

Or maybe I overlook that a nice way exists to check with AssertJ that a collection has only duplicates?

**Comment by joel-costigliola** [comment]
Could do but seems a bit too specific, you could either create a `Set` with the collection elements and check that the size is 1 or use [allSatisfy](https://javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractIterableAssert.html#allSatisfy(java.util.function.Consumer)) and check that all elements match the first one.

**Comment by pandoras-toolbox** [comment]
Okay, thanks.

**Comment by joel-costigliola** [comment]
You also have [containsOnly](https://javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/ObjectEnumerableAssert.html#containsOnly(ELEMENT...)) that counts duplicates only once so you could do: 
```java
 assertThat(List.Of("a", "a", "a")).containsOnly("a");

```
