### ISSUE TITLE
Add AbstractAssert#matchesWith

### ISSUE THREAD

**Issue by onacit** [assertj/assertj#3361]
#### Feature summary

* The [AbstractAssert#matches(java.util.function.Predicate)](https://javadoc.io/static/org.assertj/assertj-core/3.25.3/org/assertj/core/api/AbstractAssert.html#matches(java.util.function.Predicate)) covers only for a `Predicate`.
* Add an assertion method for the `BiPredicate`.

#### Example

```java
static final BiPredicate<Some, Other> thePredicate = (s, o) -> true;

final var some = new Some();
assertThat(some).matchesWith(thePredicate, new Other());
```

**Comment by scordio** [comment]
Would you have a more specific use case?
