### ISSUE TITLE
AssertJ: issue with Assertions.assertThat().usingRecursiveComparison().isEqualTo()

### ISSUE THREAD

**Issue by surinderkamboj** [assertj/assertj#3379]
**Recursive comparision is getting failed after spring boot upgrade to 3.2.1 with JDK 17.**
After spring boot upgrade the test cases are faling. Upgraded from spring boot 2.7.18 to 3.2.1.

* assertj core version:3.24.2
* java version: 17
* test framework version: Junit 5
* os (if relevant):  window

**below are the steps to reporduce the issue**

```

       public class ContactUpdateQueueModel
        {
               private String id;
               private String contactId;
               private String backend;
               private String contactType;
        }

        Map<String, Direction> sortMap = new HashMap<>();
        sortMap.put("contactId", Direction.ASC);
        sortMap.put("updateTimeStamp", Direction.ASC);
        RepositoryItemReader<ContactUpdateQueueModel> AMSactual= new RepositoryItemReader<>();
        AMSactual.setRepository(repository);
        AMSactual.setMethodName("findUpdate");
        AMSactual.setSort(sortMap);
        AMSactual.setSaveState(false);
        AMSactual.setPageSize(250);
        reader.setArguments(Arrays.asList("AMS", "PENDING"));

        Map<String, Direction> sortMap = new HashMap<>();
        sortMap.put("contactId", Direction.ASC);
        sortMap.put("updateTimeStamp", Direction.ASC);
        RepositoryItemReader<ContactUpdateQueueModel> AMSexpected = new RepositoryItemReader<>();
        AMSexpected.setRepository(repository);
        AMSexpected.setMethodName("findUpdate");
        AMSexpected.setSort(sortMap);
        AMSexpected.setSaveState(false);
        AMSexpected.setPageSize(250);
        AMSexpected.setArguments(Arrays.asList("AMS", "PENDING"));

        assertThat(AMSactual).usingRecursiveComparison().isEqualTo(AMSexpected);
```

But from version 3.24.2, we get the following instead:

```
java.lang.AssertionError: 
Expecting actual:
  org.springframework.batch.item.data.RepositoryItemReader@632ceb35
to be equal to:
  org.springframework.batch.item.data.RepositoryItemReader@1c93f6e1
when recursively comparing field by field, but found the following difference:

field/property 'lock' differ:
- actual value  : java.util.concurrent.locks.ReentrantLock@34c01041[Unlocked]
- expected value: java.util.concurrent.locks.ReentrantLock@76f4b65[Unlocked]

The recursive comparison was performed with this configuration:
- no overridden equals methods were used in the comparison (except for java types)
- these types were compared with the following comparators:
  - java.lang.Double -> DoubleComparator[precision=1.0E-15]
  - java.lang.Float -> FloatComparator[precision=1.0E-6]
  - java.nio.file.Path -> lexicographic comparator (Path natural order)
- actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).
- the introspection strategy used was: DefaultRecursiveComparisonIntrospectionStrategy

	at com.fis.payments.apex.batch.reader.TerminalContactAssignmentQueueReaderTest.testGetReader(TerminalContactAssignmentQueueReaderTest.java:62)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)

```

**Comment by joel-costigliola** [comment]
related to https://github.com/assertj/assertj/issues/3369#issuecomment-1953615601

**Comment by joel-costigliola** [comment]
At the moment, the best course of action is either ignoring the fields of type `ReentrantLock` or registering a way to compare them:

- ignoring the fields of type: [ignoringFieldsOfTypes](https://www.javadoc.io/static/org.assertj/assertj-core/3.25.3/org/assertj/core/api/RecursiveComparisonAssert.html#ignoringFieldsOfTypes(java.lang.Class...))
- registering a bi-predicate to compare certain [fields](https://www.javadoc.io/static/org.assertj/assertj-core/3.25.3/org/assertj/core/api/RecursiveComparisonAssert.html#withEqualsForFields(java.util.function.BiPredicate,java.lang.String...)) or [types](https://www.javadoc.io/static/org.assertj/assertj-core/3.25.3/org/assertj/core/api/RecursiveComparisonAssert.html#withEqualsForType(java.util.function.BiPredicate,java.lang.Class))

Just curious why you are comparing readers instead of the reader content only, IMO comparing locks fields don't make a lot of sense unless you are in a very specific context where you are managing locks explicitely.

**Comment by joel-costigliola** [comment]
Just to be extra clear, in java 17 it is illegal to use relfection on `java`/`javax` types, we have to use equals.

**Comment by surinderkamboj** [comment]
> Just to be extra clear, in java 17 it is illegal to use relfection on `java`/`javax` types, we have to use equals.

Thank you @joel-costigliola. 

But i have already used the hash code and equals method in the Model class.

**Comment by joel-costigliola** [comment]
> Just to be extra clear, in java 17 it is illegal to use relfection on java/javax types, we have to use equals.


Correction: it's only on JRE types not `javax` AFAIK

**Comment by joel-costigliola** [comment]
I have added `ignoringFieldsOfTypesMatchingRegexes(String... regexes)` since there is not much we can do for types like Locks so best is to ignore them.
