### ISSUE TITLE
Provide reason and possible replacement for  @Deprecated

### ISSUE THREAD

**Issue by maciejmiklas** [assertj/assertj#3380]
#### Feature Summary

In IDE, we rely on JavaDoc, please document the Deprecated code so we can easily replace it with a recommended solution.

#### Example

```java
  @Deprecated
  @Override
  @CheckReturnValue
  public AbstractListAssert<?, List<?>, Object, ObjectAssert<Object>> asList() {
```

**Comment by scordio** [comment]
But not mentioning on which version you're experiencing the issue, you don't find it unprofessional, right? 😉

**Comment by maciejmiklas** [comment]
3.25.1

**Comment by scordio** [comment]
Please upgrade to the latest version.

Closing as duplicate of #3327.
