### ISSUE TITLE
`AbstractOptionalDoubleAssert.hasValue(double)` fails with NaN

### ISSUE THREAD

**Issue by Caceresenzo** [assertj/assertj#3401]
**Describe the bug**

The `AbstractOptionalDoubleAssert.hasValue(double)` javadoc state that NaN values are supported (last line of):
https://github.com/assertj/assertj/blob/35e54e0571de3711f4545c0ca08d321348bbcf50/assertj-core/src/main/java/org/assertj/core/api/AbstractOptionalDoubleAssert.java#L120-L123

The nature of NaN values prevents the `==` operator to works, but there is no `hasNaNValue()` method or equivalent, and the javadoc clearly state that it should works.

* assertj core version: 3.24.2
* java version: 21
* test framework version: junit 5.10.1
* os (if relevant): windows

**Test case reproducing the bug**

```java
@Test
void testNaN() {
	assertThat(OptionalDouble.of(Double.NaN)).hasValue(Double.NaN);
}
```

Result:

```
org.opentest4j.AssertionFailedError: 
Expecting actual:
  OptionalDouble[NaN]
to contain:
  NaN
but did not.
```

**Comment by Caceresenzo** [comment]
In the meantime, that can be bypassed by testing the double value directly:
```java

@Test
void testNaN() {
	assertThat(OptionalDouble.of(Double.NaN).getAsDouble()).isNaN();
}
```

**Comment by scordio** [comment]
Thanks for reporting it, @Caceresenzo!

**Comment by scordio** [comment]
Sure, go for it, @pbacz!

**Comment by pbacz** [comment]
@scordio 
The simplest solution here would be to replace `==` comparison with `equals()` comparison.
This will have a side effect causing any test that compares `0.0` to `-0.0` to fail (currently passing).

From the javadoc stating that ```assertThat(OptionalDouble.of(Double.NaN)).hasValue(Double.NaN)``` should pass I conclude that this was always the intent to compare using `equals()`.

I propose to replace `==` check with `equals()` check and also state clearly in the javadoc which is used.

As this is potentially a breaking change for an edge case I'd like you to confirm if I should proceed with that.

**Comment by Caceresenzo** [comment]
A solution could also to add `isNaN()` to match `AbstractDoubleAssert`'s API. (and add a `isNotNaN()` too?)

This would prevent breaking changes.

**Comment by pbacz** [comment]
@Caceresenzo @scordio 
Sure, I can do it either way. All I need is a decision

**Comment by Caceresenzo** [comment]
I think having both `isNaN()` and `isNotNaN()` would be best as there do not seems to have method for the opposite of `hasValue(...)`.

Currently this passes:
```
assertThat(OptionalDouble.of(Double.NaN))
	.isNotEqualTo(Double.NaN);
```
(but I am sure its because its testing against the OptionalDouble and not the optional's value itself)

**Comment by scordio** [comment]
> I propose to replace `==` check with `equals()` check and also state clearly in the javadoc which is used.

I tend to favor this solution, consistent with what the Javadoc already states and also in line with [`OptionalDouble::equals`](https://docs.oracle.com/en%2Fjava%2Fjavase%2F21%2Fdocs%2Fapi%2F%2F/java.base/java/util/OptionalDouble.html#equals(java.lang.Object)).

It's indeed a breaking change and the workaround to get the previous behavior would be something like:

```java
assertThat(OptionalDouble.of(Double.NaN).getAsDouble()).isSameAs(Double.NaN);
```

@joel-costigliola do you agree?

**Comment by pbacz** [comment]
@scordio @joel-costigliola 
I created a PR for this issue.

**Comment by joel-costigliola** [comment]
Integrated thanks @pbacz !
