### ISSUE TITLE
Add AbstractCharSequenceAssert#doesNotHaveAny(Leading|Trailing)Whitespaces

### ISSUE THREAD

**Issue by onacit** [assertj/assertj#3433]
#### Feature summary

Sometimes, I need to verify that a `String` shouldn't have any leading/trailing whitespaces which means the [trim()](https://docs.oracle.com/javase/8/docs/api/java/lang/String.html#trim--) or [strip()](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/String.html#strip()) should be applied to the actual value.

#### Example

```java
String s = parseValue();
assertThat(s)
        .isNotNull()
        .satisfies(v -> {
            assertThat(v.strip()).isEqualTo(v); // any alternatives?
        })
       .doesNotHaveAnyLeadingWhitespaces()
       .doesNotHaveAnyTrailingWhitespaces()
;
```

**Comment by joel-costigliola** [comment]
Could be useful indeed

**Comment by yyytir777** [comment]
if you don't mind, may i take it?

**Comment by scordio** [comment]
Sure, go for it, @yyytir777!

**Comment by yyytir777** [comment]
could you assign me again? I removed it by mistake..
