### ISSUE TITLE
support for isImmutable()

### ISSUE THREAD

**Issue by hohwille** [assertj/assertj#3457]
#### Feature summary

I would love to see `assertThat(...)` to support `isImmutable()` method for the following types:
* `Iterator` - `AbstractIteratorAssert`
* `Iterable` - `AbstractIterableAssert`
* `Collection` (`List` and `Set`) - `AbstractCollectionAssert`
* `Map` - `AbstractMapAssert`

#### Example

So instead of writing all this:
```java
    assertThrows(UnsupportedOperationException.class, () -> map.put("bar", "foo"));
    assertThrows(UnsupportedOperationException.class, () -> map.remove("foo"));
    assertThrows(UnsupportedOperationException.class, () -> map.keySet().add("foo"));
    assertThrows(UnsupportedOperationException.class, () -> map.keySet().remove("foo"));
    assertThrows(UnsupportedOperationException.class, () -> {
      Iterator<String> iterator = map.keySet().iterator();
      if (iterator.hasNext()) {
        iterator.next();
        iterator.remove();
      } else {
        throw new UnsupportedOperationException();
      }
    });
    assertThrows(UnsupportedOperationException.class, () -> map.values().add("foo"));
    assertThrows(UnsupportedOperationException.class, () -> map.values().remove("foo"));
    assertThrows(UnsupportedOperationException.class, () -> {
      Iterator<Object> iterator = map.values().iterator();
      if (iterator.hasNext()) {
        iterator.next();
        iterator.remove();
      } else {
        throw new UnsupportedOperationException();
      }
    });
    MapEntry<String, Object> entry = MapEntry.entry("foo", "bar");
    assertThrows(UnsupportedOperationException.class, () -> map.entrySet().add(entry));
    assertThrows(UnsupportedOperationException.class, () -> map.entrySet().remove(entry));
    assertThrows(UnsupportedOperationException.class, () -> {
      Iterator<Entry<String, Object>> iterator = map.entrySet().iterator();
      if (iterator.hasNext()) {
        iterator.next();
        iterator.remove();
      } else {
        throw new UnsupportedOperationException();
      }
    });
```
I would like to simply write this instead getting more or less the same effect:
```
  assertThat(map).isImmutable();
```

Notes:
* elements, keys, or values can not be generated in a type-safe way. However, due to erasure and the fact that we only want to ensure that the operation immediately fails, it should be fine to use a constant `private static Object DUMMY = new Object();` as placeholder for elements, keys, or values to insert or remove.
* It seems infeasible to verify that an iterator that is empty is implemented immutable. A pragmatic approach would be to call `remove()` even if there is no next element but according to the API contract it would be unclear if also an `NoSuchElementException` may be raised. As alternative I see the option to log a warning and continue (success) or to be strict and fail the `isImmutable()` operation with an error message that it should never be invoked on empty containers. I personally prefer the more lax approach and would try to be more tolerant. Potentially there could even be variants like `isImmutableIgnoreEmptyIterator()` or adding a boolean argument as `isImmutable(boolean failOnEmptyIterator)`.

And thanks for creating the by far best assertion library that really improves live of developers a lot!

**Comment by scordio** [comment]
Would [`isUnmodifiable`](https://www.javadoc.io/static/org.assertj/assertj-core/3.25.3/search.html?q=isUnmodifiable) for `Collection` and `Map` instances help for your use case?

We plan to introduce `Iterable` support in #2974 and I just raised #3458 for `Iterator` instances 🙂

**Comment by scordio** [comment]
Closing in favor of the existing API and the additional issues mentioned in my previous message.
