### ISSUE TITLE
`isUnmodifiable` assertion for `Iterator` instances

### ISSUE THREAD

**Issue by scordio** [assertj/assertj#3458]
#### Feature summary
Similarly to #2102, we could have an `isUnmodifiable()` assertion for `Iterator` types.

#### Example

```java
Iterator<Integer> iterator = Collections.unmodifiableList(Arrays.asList(1, 2, 3)).iterator();

assertThat(iterator).isUnmodifiable();
```

**Comment by dehasi** [comment]
@scordio if nobody works on this task, I'd like to pick it up. And it seems a bit more challenging than for collections :)

**Comment by scordio** [comment]
Sure and thanks, @dehasi!

What challenges have you encountered?

**Comment by dehasi** [comment]
To be short, I can't rely on that `iterator.remove()` will throw `UnsupportedOperationException`.

I.e. `Collections.EmptyIterator.remove()` throws `IllegalStateException`. Do we treat `EmptyIterator` as unmodifiable?

But can't rely on `IllegalStateException` as unmodifiability marker. `ArrayList<>().itertator()`  can also throw  `IllegalStateException` if we haven't called `next`. 

Initially, I wanted to check unmodifiability by just calling `iterator.remove()`. It's not enough (see to ArrayList example). 
Now, I'm thinking of making an additional check like `iterator.next(); iterator.remove()`. However, it will look a bit weird.
