### ISSUE TITLE
Merge assertj-core-java17 into assertj-core

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj#3473]

**Comment by scordio** [comment]
During the work of #3442 and #3446, I realized we should have a slightly different testing strategy (see https://github.com/assertj/assertj/issues/3442#issuecomment-2078019325).

Wherever possible, we should favor extra-modular testing. while in-module testing should be used only when we want to test package-private features.

This means we should have:
* `assertj-tests/assertj-integration-tests/assertj-core-jms` for `assertj-core` for extra-modular testing
* `assertj-tests/assertj-integration-tests/assertj-guava-jms` for `assertj-guava` extra-modular testing
* `assertj-core/src/test` restricted to in-module testing

Currently, there are no package-private relevant tests for `assertj-guava` so we can avoid having `assertj-guava/src/test`.

I'm not sure if I'll be able to slice all these changes in smaller steps so I'm going to assign this one to me.

**Comment by joel-costigliola** [comment]
Should we close this issue as duplicate ?

**Comment by scordio** [comment]
Superseded by #3446.
