### ISSUE TITLE
Support for Duration in Assertions.byLessThan, Assertions.within

### ISSUE THREAD

**Issue by khmarbaise** [assertj/assertj#3486]
#### Feature summary
Enhance the `byLessThan(..)` and `within` to support the usage of `Duration`. 

At the moment `byLessThan(..)` and `within` support the usage of a value combined with a `TemporalUnit` which looks like this:

```java
assertThat(_07_10_20).isCloseTo(_07_11_45, byLessThan(1, ChronoUnit.MINUTES));
assertThat(_07_10_00).isCloseTo(_07_12_00, within(1, ChronoUnit.MINUTES));
```

#### Example
My suggestion is to enhance it in that way that you are able to use `Duration` instead of two different parameters like this:

```java
assertThat(_07_10_20).isCloseTo(_07_11_45, byLessThan(Duration.ofMinutes(1)));
assertThat(_07_10_20).isCloseTo(_07_11_45, byLessThan(Duration.ofSeconds(45)));
```
or as example for `within`:

```java
assertThat(_07_10_00).isCloseTo(_07_12_00, within(Duration.ofMinutes(1)));
```

**Comment by scordio** [comment]
Indeed, it would be a nice addition!

**Comment by etrandafir93** [comment]
@scordio - I guess we just need some simple static factory methods. Can i work on this?
