### ISSUE TITLE
3.26 - Ambiguous assertThat with Temporal implementation

### ISSUE THREAD

**Issue by mikethecalamity** [assertj/assertj#3494]
**Describe the bug**
When I tried upgrading my system to `3.26.0`, I now get an error for assertions with an implementation of `Temporal`. See error and class details below.

* assertj core version: 3.26.0
* java version: JDK 17
* test framework version: JUnit 5

**Error**
```
error: reference to assertThat is ambiguous
        assertThat(b.getTime()).isSameAs(t);
        ^
  both method <T>assertThat(T) in Assertions and method assertThat(Temporal) in Assertions match
  where T is a type-variable:
    T extends Comparable<? super T> declared in method <T>assertThat(T)
```

**Test case reproducing the bug**

```java
public class MyTemporal implements Temporal, Serializable, Comparable<Instant> {
    ...
}
```

```java
public class MyPojo {
    private MyTemporal time;

    public MyTemporal getTime() {
        return time;
    }
}
```

**Comment by scordio** [comment]
Thanks for reporting it, @mikethecalamity!

I generalized the title of #3491 so I'm closing this one as a duplicate.
