### ISSUE TITLE
Extra variant for doesNotMatch

### ISSUE THREAD

**Issue by ununhexium** [assertj/assertj#3497]
#### Feature summary

`org.assertj.core.api.AbstractCharSequenceAssert#matches(java.lang.CharSequence)`

and

`org.assertj.core.api.AbstractAssert#matches(java.util.function.Predicate<? super ACTUAL>)`

exists but its counterpart `doesNotMatch` only has 

`org.assertj.core.api.AbstractCharSequenceAssert#doesNotMatch(java.lang.CharSequence)`

and doesn't have

`org.assertj.core.api.AbstractAssert#doesNotMatch(java.util.function.Predicate<? super ACTUAL>)`

#### Example

```java
assertThat(actualString)
    .matches(it -> it.startsWith("foo"))
    .doesNotMatch(it -> it.endsWith("bar")); // nope, not available
```

May I add it?

**Comment by brunodmartins** [comment]
Can I work on this issue?
