### ISSUE TITLE
reference to assertThat is ambiguous when asserting a `java.time.Year`

### ISSUE THREAD

**Issue by thunderhook** [assertj/assertj#3516]
**Describe the bug**

Since 3.26.0 we cannot use `assertThat` on a `java.time.Year`: `reference to assertThat is ambiguous`

* assertj core version: 3.26.0
* java version: 17
* test framework version: JUnit5

**Test case reproducing the bug**

```java
import org.junit.jupiter.api.Test;

import java.time.Year;

import static org.assertj.core.api.Assertions.assertThat;

class YearDemo {

	@Test
	void testYear() {

		Year year = Year.now();

		// java: reference to assertThat is ambiguous
		//  both method <T>assertThat(T) in org.assertj.core.api.Assertions and method assertThat(java.time.temporal.Temporal) in org.assertj.core.api.Assertions match
		assertThat(year).isEqualTo(Year.now());
	}
}

```

**Comment by scordio** [comment]
Thanks for reporting it, @thunderhook!

The same was reported in #3491 and will be addressed in [3.26.1](https://github.com/assertj/assertj/milestone/75).

As a temporary workaround, you can cast `year` to a `Temporal`:

```java
assertThat((Temporal) year).isEqualTo(Year.now());
```

In light of that, I'm closing this one as a duplicate.
