### ISSUE TITLE
comparingOnlyFields get data of all fields

### ISSUE THREAD

**Issue by GuillaumeC** [assertj/assertj#3533]
When using comparingOnlyFields with usingRecursiveComparison assertions, all of my entity fields are loaded, but only want I want is compared.
The problem is that if I have Lazy fields that are not in my comparison list, they will be loaded, and a LazyException will be thrown.

Only wanted fields should be loaded in the comparison map.

* assertj core version: 3.24.2
* java version: 21
* test framework version: jUnit 5.10.2
* os (if relevant): 

**Test case reproducing the bug**
We need 2 entities linked by a ManyToOne for example a User with his City
We get the 1st entity and we want to test only his name and his id comparing to a given dto
We will write:

MyEntityDto dto = new MyEntityDto().setName("test").setId(1);
assertThat(myEntity).usingRecursiveComparison().comparingOnlyFields("name", "id").isEqualsTo(dto);

But test will failed with Lazy exception on myEntity.city, even if I don't ask to compare this field.

```java
import javax.persistence.*;

@Entity
public class City {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String name;
    private String postalCode;
}

@Entity
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String firstName;
    private String lastName;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "city_id")
    private City birthCity;
}


import org.springframework.data.jpa.repository.JpaRepository;

public interface CityRepository extends JpaRepository<City, Long> {
}

public interface UserRepository extends JpaRepository<User, Long> {
}


import static org.assertj.core.api.Assertions.assertThat;

import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;

@DataJpaTest
public class UserRepositoryTest {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private CityRepository cityRepository;

    @Test
    public void testSaveAndRetrieveUser() {
        // Create and save a City
        City city = new City();
        city.setName("Paris");
        city.setPostalCode("75000");
        city = cityRepository.save(city);

        // Create and save a User
        User user = new User();
        user.setFirstName("John");
        user.setLastName("Doe");
        user.setBirthCity(city);
        user = userRepository.save(user);

        // Retrieve the created user
        User retrievedUser = userRepository.findById(user.getId()).orElse(null);

        // Verify the fields of the retrieved user
        assertThat(retrievedUser).isNotNull();
        assertThat(retrievedUser).usingRecursiveComparison().comparingOnlyFields("firstName", "lastName").isEqualTo(user);
    }
}

```

I'm hoping to be clear.

Thanks for your time !

**Comment by scordio** [comment]
Thanks for reporting it, @GuillaumeC!

**Comment by joel-costigliola** [comment]
Indeed, we could try to evaluate if fields are candidates for comparison without accessing their values, I'm not yet 100% sure it is possible, if introspecting a `java.lang.reflect.Field` forces JPA to load it then it won't work since we have to introspect fields.

I'll test that this week.

**Comment by joel-costigliola** [comment]
@GuillaumeC could you tell us what dependencies we should use to reproduce the test case ? 

I'm guessing some spring modules, but which ones exactly and with which versions, thanks !

**Comment by joel-costigliola** [comment]
@GuillaumeC I don't know much about spring boot and so far I haven't been able to compile the test. 
![image](https://github.com/user-attachments/assets/53b9d282-1c06-4996-8b56-e30f395ee36b)

Do you know what I'm missing here ? 

Maybe It could be easier if you could create a zip with a project reproducing the test if that's not too much work for you ?

**Comment by GuillaumeC** [comment]
I will do it. I need just a little free time to do it.

**Comment by joel-costigliola** [comment]
No rush, take your time and thanks

**Comment by GuillaumeC** [comment]
I'm trying to reproduce with a simple project, but I cannot understand why in my test, my Lazy variable doesn't make any problem (while I see it Lazy), when in my project I have a LazyException throwing.

In the method     Set<String> getActualChildrenNodeNamesToCompare(DualValue dualValue), (RecursiveComparisonConfiguration.java:401)

Gettings node names is ok (getChildrenNodeNamesOf(dualValue.actual)).
After that, a filter is apply shouldIgnoreFieldBasedOnFieldLocation.
Alfter, and before others filters (I don't know why), we get the data values into an DualValue, with method private DualValue dualValueForField(DualValue parentDualValue, String fieldName) (line 430).

In this object, we set the actual value and expected value into DualValue, and when this DualValue is return, in my project, an LazyException is throwned.
But in my mini project, I can see that my value is Lazy with debug, but no exception is thown :-(

In my opinion, shouldBeCompared has to be used before getting field value (for the location part), and after for the value part.


I'm trying a little more to build a project with the Exception throwing.

**Comment by GuillaumeC** [comment]
@joel-costigliola 

Seems that DualValue.toString() was called in my project (may be by a log or something like that), when method dualValueForField is returning the DualValue object. toString read values, even if they are lazy, and this is why I have a LazyException.

**Comment by GuillaumeC** [comment]
@joel-costigliola 

Sorry for the spam. I DID IT !
[demo.zip](https://github.com/user-attachments/files/16378979/demo.zip)

To reproduce the case, we need an entity linked to a **Set** of another entity.
Hibernate calls the hashCode method of the DualValue and it Throws the Lazy Exception.

**Comment by joel-costigliola** [comment]
Awesome, thanks ! I'll try the demo over the weekend

My first thoughts are that if the issue is really the `hashCode` of `DualValue`, we could address it by not using values to compute the hash code but only the field location, it would work, but I'm not sure what the impact would be performance wise.

**Comment by joel-costigliola** [comment]
The test succeeds with our latest version but you have to exclude the assertj core version from the spring boot dependency, I changed the pom to 
```xml
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-test</artifactId>
			<scope>test</scope>
			<exclusions>
				<exclusion>
					<groupId>org.assertj</groupId>
					<artifactId>assertj-core</artifactId>
				</exclusion>
			</exclusions>
		</dependency>

		<dependency>
			<groupId>org.assertj</groupId>
			<artifactId>assertj-core</artifactId>
			<version>3.26.3</version>
			<scope>test</scope>
		</dependency>
```

@GuillaumeC can you give a try and see if it works on your side ?

**Comment by scordio** [comment]
@GuillaumeC as you use the `spring-boot-starter-parent`, you can tune the AssertJ version via the `assertj.version` build property – more at https://assertj.github.io/doc/#spring-boot

**Comment by GuillaumeC** [comment]
@joel-costigliola @scordio 
It's works ! Thank a lot for your time !
So I migrated my project to the last version of assertj with the assertj.version build property.

Have a nice day
