### ISSUE TITLE
AllOf should report which condition failed 

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj#3537]
#### Feature summary

See https://stackoverflow.com/questions/78745304/assertj-how-to-know-which-conditions-failed-when-using-allof/78747459#78747459

#### Example

```java
Condition<String> condition1 = new Condition<String>(text -> text != null, "Input not null");
Condition<String> condition2 = new Condition<String>(text -> text.equalsIgnoreCase("abc"), "Input not matching");
assertThat(someString).satisfies(allOf(condition1, condition2));
```

**Comment by JunHyungJang** [comment]
It looks interesting ! Can i get this issue?

**Comment by joel-costigliola** [comment]
Sure thanks @JunHyungJang

**Comment by injae-kim** [comment]
![image](https://github.com/user-attachments/assets/d3fcbb7b-bca0-498f-9a59-bdfadb9ba0c4)

Now we can check which condition failed inside allOf 👍
