### ISSUE TITLE
`inBinary` not exposed for `String` assertions

### ISSUE THREAD

**Issue by scordio** [assertj/assertj#3547]
There is a test that demonstrates the use of `inBinary` with `String` assertions:

https://github.com/assertj/assertj/blob/63e56f88d74bd5b44bb942382c49f29f38906d94/assertj-core/src/test/java/org/assertj/core/api/Assertions_assertThat_inBinary_Test.java#L107-L112

However, `inBinary` is not made `public` in `AbstractStringAssert` and cannot be used by client code.

**Comment by sunaleed** [comment]
https://github.com/assertj/assertj/pull/3600
I created a PR for this issue

**Comment by scordio** [comment]
Done in a4bc7ecc.
