### ISSUE TITLE
Using withComparatorForType with Kotlin

### ISSUE THREAD

**Issue by jamesmudd** [assertj/assertj#3589]
**Describe the bug**
When trying to override the comaprator used in a recursive comparison the overriden one is setup but not used. This is probably because of Kotlin mapped types https://kotlinlang.org/docs/java-interop.html#mapped-types

It also appears nearly impossible to override the `java.lang.Double` comparator via Kotlin, not sure if this should be possible or not.

* assertj core version: 3.24.1
* java version: 21
* test framework version: junit 5.10.1 - not relevant
* os (if relevant): macOS  - not relevant

**Test case reproducing the bug**

This can run as a `.kts` Kotlin script
```kotlin
import org.assertj.core.api.Assertions.assertThat
import org.assertj.core.util.DoubleComparator

data class Item(val name: String, val price: Double)

val hat = Item("hat", 12.34)
val otherHat = Item("hat", 12.34000000000001)

assertThat(hat).usingRecursiveComparison()
    .withComparatorForType(DoubleComparator(0.0005), Double::class.java)
    .isEqualTo(otherHat)
```
Here is the output
```
Exception in thread "main" java.lang.AssertionError: 
Expecting actual:
  Item(name=hat, price=12.34)
to be equal to:
  Item(name=hat, price=12.34000000000001)
when recursively comparing field by field, but found the following difference:

field/property 'price' differ:
- actual value  : 12.34
- expected value: 12.34000000000001

The recursive comparison was performed with this configuration:
- no overridden equals methods were used in the comparison (except for java types)
- these types were compared with the following comparators:
  - double -> DoubleComparator[precision=5.0E-4]
  - java.lang.Double -> DoubleComparator[precision=1.0E-15]
  - java.lang.Float -> FloatComparator[precision=1.0E-6]
  - java.nio.file.Path -> lexicographic comparator (Path natural order)
- actual and expected objects and their fields were compared field by field recursively even if they were not of the same type, this allows for example to compare a Person to a PersonDto (call strictTypeChecking(true) to change that behavior).
- the introspection strategy used was: DefaultRecursiveComparisonIntrospectionStrategy
```

So it appears that while the comparator was added `double -> DoubleComparator[precision=5.0E-4]` it was not used for the comparison?

**Comment by scordio** [comment]
Thanks for reporting it, @jamesmudd! We'll look into it and get back to you.

**Comment by scordio** [comment]
The registered comparator is for the `double` primitive type and not for `java.lang.Double`:

```
double -> DoubleComparator[precision=5.0E-4]
```

The Kotlin example behaves like the following Java code, which also fails:

```java
record Item(String name, Double price) {
}

@Test
void test() {
  var hat = new Item("hat", 12.34);
  var otherHat = new Item("hat", 12.34000000000001);

  assertThat(hat).usingRecursiveComparison()
    .withComparatorForType(new DoubleComparator(0.0005), Double.TYPE)
    .isEqualTo(otherHat);
}
```

If `Double::class.java` refers to the `double` primitive, what is the proper way in Kotlin to refer to `java.lang.Double`?

We probably have problems due to autoboxing, which needs to be checked better, but I'd argue that the primitive type comparator should be considered.

**Comment by scordio** [comment]
This passes 🙈

```kotlin
val hat = Item("hat", 12.34)
val otherHat = Item("hat", 12.34000000000001)

assertThat(hat).usingRecursiveComparison()
  .withComparatorForType(DoubleComparator(0.0005), (0.0 as Double?)?.javaClass)
  .isEqualTo(otherHat)
```

**Comment by scordio** [comment]
> If `Double::class.java` refers to the `double` primitive, what is the proper way in Kotlin to refer to `java.lang.Double`?

Today, I learned the proper way from [a tweet](https://x.com/tagir_valeev/status/1846184680652992955) of @amaembo: `Double::class.javaObjectType`.

So your example would become the following:

```kotlin
val hat = Item("hat", 12.34)
val otherHat = Item("hat", 12.34000000000001)

assertThat(hat).usingRecursiveComparison()
  .withComparatorForType(DoubleComparator(0.0005), Double::class.javaObjectType)
  .isEqualTo(otherHat)
```

which indeed passes.

> I'd argue that the primitive type comparator should be considered.

After a few weeks of digesting this idea, and given that there is a way to register the comparator properly, I'm no longer convinced we should introduce such an implicit behavior, which would remove the fine-grained control possible today.

In light of that, I am closing this issue, but let us know if you need anything else.

**Comment by vlsi** [comment]
> but I'd argue that the primitive type comparator should be considered.

I am afraid Java does not support "primitive `Comparator<double>`", so `Comparator` must be of `Comparator<java.lang.Double>` type, so it could make sense to auto-box when searching for the comparator.

In other words, as assertj detects a `double` value, it could check both comparators for `double` and `java.lang.Double`.

Imagine user have both boxed and non-boxed doubles. It probably makes sense registering a comparator only once so it is used for both doubles.

**Comment by scordio** [comment]
> I am afraid Java does not support "primitive `Comparator<double>`", so `Comparator` must be of `Comparator<java.lang.Double>` type, so it could make sense to auto-box when searching for the comparator.

Yes, definitely, but you can still "attach" that comparator to the primitive type only. See the example at https://github.com/assertj/assertj/issues/3589#issuecomment-2312880315.

> Imagine user have both boxed and non-boxed doubles. It probably makes sense registering a comparator only once so it is used for both doubles.

I had the same in mind, but I want to keep the option for users who want fine-grained control, which is possible today, given that the price to pay is the double registration (pun intended).
