### ISSUE TITLE
Support Function in `hasNoNullFieldsOrPropertiesExcept` and `hasAllNullFieldsOrPropertiesExcept`

### ISSUE THREAD

**Issue by thunderhook** [assertj/assertj#3616]
#### Feature summary

There are some cases where we want to check if everything is set except some fields. For this we use `hasNoNullFieldsOrPropertiesExcept("id")`. This is handy, but has the disadvantage that it may be overlooked when refactoring some of the underlying classes. So it would be nice to provide a function instead of the field/property name.

I'm not sure I want to provide something like this myself, as it bloats the API (and we really don't use it that much). Another drawback is that this could be abused, see the example beyond.

What do you think?

#### Example

```java
public class AssertJExampleTest {

    @Test
    void assertThatHasNoNullFieldsExceptFunction() {

        PersonEntity peter = new PersonEntity( null, "Peter" );

        assertThat(peter)
            .hasNoNullFieldsOrPropertiesExcept(
                PersonEntity::getNullableString, // or p -> p.getNullableString()
                BaseEntity::getId

                // but this could be abused like
                // p -> p.doSomething().calculate().thenReturnSomething()
            );
    }
}
// imagine having getters
class BaseEntity {
    Long id;
}
class PersonEntity extends BaseEntity {
    String name;
    String nullableString;
}
```

**Comment by scordio** [comment]
`hasNoNullFieldsOrPropertiesExcept(String)` works in principle with reflection to enumerate all the fields.

How could a `Function` help identify the fields/properties to exclude? As you also mentioned, functions are not necessarily getters only, so I imagine AssertJ's input would be the resulting value, which I find a bit fragile.

Do you see a more robust strategy for skipping fields/properties via functions?

**Comment by scordio** [comment]
A refactoring-safe alternative might be a combination of `returns` and `doesNotReturn`, but this has the disadvantage of explicitly mentioning all the fields/properties.

For example:

```java
assertThat(peter)
  .returns(null, from(PersonEntity::getNullableString))
  .returns(null, from(PersonEntity::getNullableString))
  .doesNotReturn(null, from(PersonEntity::getName));
```

**Comment by thunderhook** [comment]
> How could a `Function` help identify the fields/properties to exclude?

It would not help, it would just
* Be automatically renamed when the getter is renamed using an IDE
* Provide a compile error if not

> As you also mentioned, functions are not necessarily getters only, so I imagine AssertJ's input would be the resulting value, which I find a bit fragile.

I agree, that's what I meant with misusing it.

We often use `extracting(...)` in our code base and never use the field names, but only getters as functions because of the reasons above. I just thought about - kind of - aligning it here.

**Comment by scordio** [comment]
What I meant is, how would you imagine the implementation?

Obtaining the result of the function/lambda and comparing it with the current value of one of the fields would only be reliable if only a single field has the same value.

Is https://github.com/assertj/assertj/issues/3616#issuecomment-2364584383 a reasonable alternative for your use case?

**Comment by thunderhook** [comment]
Thanks for the quick response.

> `hasNoNullFieldsOrPropertiesExcept(String)` works in principle with reflection to enumerate all the fields.

I did not read that carefully last time, sorry.
Yes, in this sense functions cannot really help. The reflection also checks hidden fields that can't be accessed via getters, so that wouldn't help either.

> Is https://github.com/assertj/assertj/issues/3616#issuecomment-2364584383 a reasonable alternative for your use case?

I have to re-check our code where we use `hasNoNullFieldsOrPropertiesExcept("id")` but I don't think it would help since our object have like 15 fields or more, most of them having an "id" or "creationTimestamp" that can be null. I didn't write these assertions and didn't know about `hasNoNullFieldsOrPropertiesExcept` before.

That said, maybe we should just adapt our tests and do proper assertions of all those fields. I think the developer at the time was just lazy.

I think this issue can be closed then. Thanks!

**Comment by scordio** [comment]
> I don't think it would help since our object have like 15 fields or more

I imagined you'd be facing such a use case 🙂 

> I think this issue can be closed then. Thanks!

Sure, and thanks to you! Please let us know if you see anything more to discuss.
