### ISSUE TITLE
Fluent ThrowableAssertAlternative methods do not offer the ability to ignore case on matched string

### ISSUE THREAD

**Issue by DorianNaaji** [assertj/assertj#3628]
#### Feature summary

ThrowableAssertAlternative.withMessageContaining(String description) method does not offer the ability to ignore case

#### Example

```java
// My test code
  @Test
  void insertSelfReferencingEntite_shouldRaiseConstraintViolationException() {
    assertThatExceptionOfType(ConstraintViolationException.class).isThrownBy(() -> someService.insertEntiteAttachedToItself())
            .withMessageContaining("check_entite_rattachement_id_not_self_referencing");
  }

// Console output
Expecting throwable message:
  "could not execute statement [Check constraint violation: "CHECK_ENTITE_RATTACHEMENT_ID_NOT_SELF_REFERENCING: "; SQL statement:
insert into entite 
(...)
to contain:
  "check_entite_rattachement_id_not_self_referencing"
but did not.

Throwable that failed the check:

org.hibernate.exception.ConstraintViolationException: could not execute statement [Check constraint violation: "CHECK_ENTITE_RATTACHEMENT_ID_NOT_SELF_REFERENCING: "; SQL statement:
```

Minor feature request: Wouldn't it be nice to have the ability to ignore case or have extra control on how the final assertion is made with these kind of fluent assertions? Just dropping that here in case that's a good idea ✅

**Comment by joel-costigliola** [comment]
You could use [withMessageMatching](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/ThrowableAssertAlternative.html#withMessageMatching(java.lang.String)) and set the regex to be [case insensitive](https://www.baeldung.com/java-case-insensitive-string-matching#string-matches).
