### ISSUE TITLE
Allow supplying predicate description to `anyMatch` and `noneMatch`

### ISSUE THREAD

**Issue by jh-instant** [assertj/assertj#3638]
#### Feature summary
It would be helpful to be able to supply a custom predicate description to all predicate-based iterable assertions (`allMatch`, `anyMatch` and `noneMatch`). Currently only `allMatch` allows supplying a custom predicate description.

From [the docs](https://assertj.github.io/doc/#match) (under the example for all 3):
> "You can pass a predicate description to make the error message more explicit if the assertion fails" under the example of all three.

It would be good to keep the docs aligned to the functionality, although in this case aligning the functionality to the docs would be preferable.

#### Example
```java
List<String> myList = List.of("a", "b", "cc");
assertThat(myList).allMatch(entry -> entry.length() == 2, "length of 2"); // ✅
assertThat(myList).anyMatch(entry -> entry.length() == 2, "length of 2"); // ❌
assertThat(myList).noneMatch(entry -> entry.length() == 2, "length of 2"); // ❌
```

**Comment by joel-costigliola** [comment]
Agreed, thanks for the PR !

**Comment by joel-costigliola** [comment]
closed by https://github.com/assertj/assertj/pull/3639
