### ISSUE TITLE
Ability to see rawClass in InstanceOfAssertFactory

### ISSUE THREAD

**Issue by lukas-krecan** [assertj/assertj#3653]
#### Feature summary
I am author of JsonUnit. I would like to support `InstaceOfAssertFactory` based asserts, for example:

```
assertThatJson("{\"a\":[1, 2, 3]}").inPath("a").isArray().last(as(INTEGER)).isEqualTo(3);
```

The trouble is that there can be many different types in the JSON. Form the code it seems straightforward to override the `asInstanceOf` method

```
    @Override
    public <ASSERT extends AbstractAssert<?, ?>> ASSERT asInstanceOf(InstanceOfAssertFactory<?, ASSERT> instanceOfAssertFactory) {
        Class<?> rawClass = getRawClass(instanceOfAssertFactory);
        if (rawClass.equals(Integer.class)) {
            Node node = assertType(NUMBER);
            if (!node.isIntegralNumber()) throw new AssertionError("Node \"" + path + "\" can not be converted to integer");
            return new IntegerAssert(node.decimalValue().intValue()).asInstanceOf(instanceOfAssertFactory);
        }
        if (rawClass.equals(BigDecimal.class)) {
            return isNumber().asInstanceOf(instanceOfAssertFactory);
        }
        // More ifs here
        throw new UnsupportedOperationException("TODO");
    }
```

The issue is that it's not possible to implement `getRawClass` without reflection as the method is package protected. Would it be possible to make it public or provide other means how to prepare values for InstanceOfAssertFactory so the cast passes?

[Here](https://github.com/lukas-krecan/JsonUnit/compare/v4...InstanceOfAssertFactory?expand=1) is scatch of the idea

**Comment by lukas-krecan** [comment]
Sorry, I discovered other issues that prevent full support of InstanceOfAssertFactory so this is not relevant any more. Thanks for understanding

**Comment by scordio** [comment]
Hi @lukas-krecan, no problem!

In case you solve the issues you just found, I wanted to let you know that we introduced a new `createAssert(ValueProvider)` default method to `AssertFactory` in #3377. This method allows client code to perform type-aware conversions before the cast happens.

See for example the snippet at https://github.com/assertj/assertj/pull/3377#issuecomment-2017372973.

**Comment by scordio** [comment]
On a related note, I applied `createAssert(ValueProvider)` for internal usage in 7c657bc4, and `getRawClass` no longer exists.
