### ISSUE TITLE
Using RecursiveComparisonConfiguration withIgnoredFields for Map

### ISSUE THREAD

**Issue by Pawlaklis** [assertj/assertj#3675]
**Describe the bug**
I'm not sure if it's a bug, or should it be a feature request.
I tried to compare two maps while ignoring a field similarly to https://assertj.github.io/doc/#assertj-core-recursive-comparison-for-iterable 

* assertj core version: 3.26.3
* java version: 21 (temurin-21.0.5) 
* test framework version: junit-jupiter 5.11.3

**Test case reproducing the bug**

When asserting if two maps are equal using `usingRecursiveComparison` and `withIgnoredFields("age")` assertion fails

```java
import org.assertj.core.api.recursive.comparison.RecursiveComparisonConfiguration;
import org.junit.jupiter.api.Test;

import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class AssertJTestTest {
    record Person(String name, int age) {
    }

    @Test
    void testAssertJ() {
        Person john = new Person("John", 30);
        Person olderJohn = new Person("John", 60);


        assertThat(john)
                .usingRecursiveComparison(
                        RecursiveComparisonConfiguration.builder()
                                .withIgnoredFields("age")
                                .build()
                )
                .isEqualTo(olderJohn);
    }

    @Test
    void testAssertJ_ignoreFields() {
        var john = new Person("John", 30);
        var mapWithJohn = Map.of("john_id", john);

        var olderJohn = new Person("John", 60);
        var mapWithOlderJohn = Map.of("john_id", olderJohn);


        assertThat(mapWithJohn)
                .usingRecursiveComparison(
                RecursiveComparisonConfiguration.builder()
                        .withIgnoredFields("age")
                        .build()
                )
                .isEqualTo(mapWithOlderJohn);

        /* fails with the following error:
         * java.lang.AssertionError:
         * Expecting actual:
         *   {"john_id"=Person[name=John, age=30]}
         * to be equal to:
         *   {"john_id"=Person[name=John, age=60]}
         * when recursively comparing field by field, but found the following difference:
         *
         * field/property 'john_id.age' differ:
         * - actual value  : 30
         * - expected value: 60
         */
    }

}
```

This can be avoided by using `withIgnoredFieldsMatchingRegexes(".*age")` instead of `withIgnoredFields("age")`

**Comment by joel-costigliola** [comment]
It is the correct behavior as you need to set the complete path to the field when using `withIgnoredFields`, in your case that would be `john_id.age` but if you can't know `john_id` value in advance then using `withIgnoredFieldsMatchingRegexes` is the right way to go.

Basically, we introduced `withIgnoredFieldsMatchingRegexes` to get around the limitation of `withIgnoredFields` that requires knowing the exact path to the fields you want to ignore.

**Comment by Pawlaklis** [comment]
Thank you for the explanation!
