### ISSUE TITLE
Support specialized equality methods

### ISSUE THREAD

**Issue by devinrsmith** [assertj/assertj#3678]
#### Feature summary
Often times, classes define specialized equality methods that have different semantics than `Object#equals`. It would be nice to be able to reference these directly via a `BiPredicate<T, T>` and have it work with `isEqualTo` and other relevant methods.

#### Example

```java
assertThat(actual)
    .usingEqualityMethod((x, y) -> x.equalsStrict(y))
    .isEqualTo(expected);

// or

assertThat(actual)
    .usingEqualityMethod(MyObject::equalsStrict)
    .isEqualTo(expected);
```

I can currently hack around this by (ab)using `usingComparator`, but it's not ideal.

```java
assertThat(actual)
    .usingComparator((x, y) -> x.equalsStrict(y) ? 0 : -1)
    .isEqualTo(expected)
```

**Comment by joel-costigliola** [comment]
I agree allowing to express `equals` with `BiPredicate<T, T>` would be nice.

Would `usingEquals` be as clear as `usingEqualityMethod` ? No strong opinion on my side, just thinking of other namings

**Comment by devinrsmith** [comment]
`usingEquals` is a less verbose and makes sense to me.

**Comment by joel-costigliola** [comment]
PR welcomed 😉
