### ISSUE TITLE
`contains` after `extracting(Function...)` no longer accepts values with ancestor type

### ISSUE THREAD

**Issue by scordio** [assertj/assertj#3709]
The following compiles with 3.26.3:

```java
record Container(String name, ArrayList<Object> elements) {
}

Container container = new Container("", new ArrayList<>());

assertThat(container)
  // returns AbstractListAssert<?, List<?>, Object, ObjectAssert<Object>>
  .extracting(Container::name, Container::elements)
  .contains("", List.of());
```

However, it doesn't compile with 3.27.0:

```java
assertThat(container)
  // returns AbstractListAssert<?, List<? extends Serializable>, Serializable, ObjectAssert<Serializable>>
  .extracting(Container::name, Container::elements)
  .contains("", List.of()); // Cannot resolve method 'contains(String, List<E>)'
```

This is a consequence of:
* #3673

which changed the minimum accepted type of `contains` values from `Object` to `Serializable`.

Arguably, the following wouldn't compile even with 3.26.3:

```java
assertThat(List.of(container.name(), container.elements()))
  .contains("", List.of()); // Cannot resolve method 'contains(String, List<E>)'
```

Therefore, I'm unsure whether the previous behavior of `extracting` chained with `contains` should be supported.

The workaround for both examples is to create an `ArrayList` from the expected `List`:

```java
assertThat(container)
  .extracting(Container::name, Container::elements)
  .contains("", new ArrayList<>(List.of()));

assertThat(List.of(container.name(), container.elements()))
  .contains("", new ArrayList<>(List.of()));

**Comment by scordio** [comment]
**Team decision:** we don't feel something should be fixed.

If anyone else faces the same issue, please share the use case details so we can re-evaluate the decision.

**Comment by ppkarwasz** [comment]
We are slightly affected by this change in apache/logging-log4j2#3365.

The issue requires a 2 LoCs change, so I don't think it should be reverted. It should IMHO be documented in the release notes as "Source incompatibility".

**Comment by scordio** [comment]
Thanks for the suggestion, @ppkarwasz. I'll mention it as a breaking change due to https://github.com/assertj/assertj/issues/3728#issuecomment-2574084137.

**Comment by scordio** [comment]
@ppkarwasz the breaking change is now mentioned in the release notes of [3.27.0](https://github.com/assertj/assertj/releases/tag/assertj-build-3.27.0), with the following description:

> Before this change, `extracting(Function...)` changed `actual` to a list of `Object` instances, even in cases where the resulting objects could have had a more specific common supertype. With this change, the element type of the returned list is narrowed down to the common supertype of the resulting elements, allowing the compiler to accept chained assertions specific to the common supertype.
> 
> However, this can break existing code, like in #3709.
> 
> In addition, this can break existing code based on Kotlin 1.9, like in #3728. In such cases, either upgrade Kotlin to 2.x or upgrade AssertJ to 3.27.3, which restores compatibility with Kotlin 1.9.
