### ISSUE TITLE
`usingComparatorForFields` and `usingComparatorForType` documentation example using deprecated method

### ISSUE THREAD

**Issue by origin-coding** [assertj/assertj#3711]
Ducumentation links:
https://www.javadoc.io/static/org.assertj/assertj-core/3.23.1/org/assertj/core/api/AbstractObjectAssert.html#usingComparatorForFields(java.util.Comparator,java.lang.String...)

https://www.javadoc.io/static/org.assertj/assertj-core/3.23.1/org/assertj/core/api/AbstractObjectAssert.html#usingComparatorForType(java.util.Comparator,java.lang.Class)

Description:
These two methods' code example uses a method called "isEqualToComparingFieldByField" and "isEqualToIgnoringNullFields".
Such methods are actually marked as **Deprecated** which means **they are not supported**.
So is there any plan to change the documentation using the new **"RecursiveComparisonConfiguration"** class?

**Comment by joel-costigliola** [comment]
Since `usingComparatorForFields` is only used by deprecated assertions, I'll deprecate it too.

It's not quite the case for `usingComparatorForType` that is used in `returns` and `doesNotReturn` assertions, so we will keep it for now.
