### ISSUE TITLE
as() description does not show up in test output

### ISSUE THREAD

**Issue by arnonmoscona** [assertj/assertj#523]
`as()` and `describedAs()` are very useful, but the problem is that they do not show up in the test output (using JUnit 4.12 in IntelliJ IDEA). 

I would expect that when an assertion fails, the description would be emitted as part of the test output. At least in my case the description is absent from the output and is currently functioning as little more then a comment.

**Comment by mkordas** [comment]
@arnonmoscona 
Can you share your code, the output you are getting and the output you expect?

**Comment by arnonmoscona** [comment]
OK. Here goes. Mind you, I am doing this all inside IDEA so the text is not exactly like what you get from the command line (IDEA JUnit plugin adds some lines of its own). The example test class looks like this:
```java
import org.junit.Test;
import static org.assertj.core.api.Assertions.*;

/**
 * example of a test with as()
 */
public class AssertJExample {
    /**
     * Tests as()
     */
    @Test
    public void testAs() throws Exception {
        int x = 1;
        assertThat(x<0).isTrue().as("X has the wrong value. Expected to be negative.");
    }
}
```
This is written to fail, obviously. Here's the relevant part of the output (skipping lots of noise):

>com.moscona.util.async.furtures.AssertJExample
>org.junit.ComparisonFailure: 
>Expected :true
>Actual   :false
>...
>at com.moscona.util.async.furtures.AssertJExample.testAs(AssertJExample.java:33)
>...

This output has no trace of the description provided in the `as()` method. I would expect to get something along the lines of:

>com.moscona.util.async.furtures.AssertJExample
>org.junit.ComparisonFailure: 
>Expected :true
>Actual   :false
>  
>Described as: "X has the wrong value. Expected to be negative."
>...
>at com.moscona.util.async.furtures.AssertJExample.testAs(AssertJExample.java:33)
>...

The error without the description in the output is often cryptic. It just tells you what comparison failed, but nothing else. When using soft asserts, the problem is compounded. When the description is not present you cannot really distinguish which assertion failed without referring to the source. Suppose, for instance that we had 3 soft assertions and they were all boolean expectations. One or two failed, but which one(s)?

**Comment by joel-costigliola** [comment]
You need to use `as()` before the assertion because a failing assertion stops the chained methods called afterwards.
It should be better documented as I already have seen this misuse before.

**Comment by arnonmoscona** [comment]
Ah!

I completely missed that. Maybe just a comment on the web site would help avoid this error...

**Comment by joel-costigliola** [comment]
will do.

**Comment by joel-costigliola** [comment]
Clarification made in Javadoc  (next version) and in the [web site](http://joel-costigliola.github.io/assertj/assertj-core-features-highlight.html#describe-assertion).

**Comment by adzest** [comment]
@joel-costigliola found that this is not showing as() method correctly:
Case NOT displayed:
`Assertions
.assertThat("ward")
.as("Custom message")
.asString()
.containsPattern(".*ord");
`
out: 
`java.lang.AssertionError: 
Expecting actual:
  "test"
to contain pattern:
  "ord"`

Case displayed:
`Assertions
.assertThat("ward")
.as("Custom message")
.asString()
.containsPattern(".*ord")`
out:
`java.lang.AssertionError: [Custom message] 
Expecting actual:
  "test"
to contain pattern:
  "ord"`

version: 3.20.0
can you pls add more details to docs.

**Comment by joel-costigliola** [comment]
Indeed `asString()` forgets about the previously set description.
