### ISSUE TITLE
Assertions on list of lists

### ISSUE THREAD

**Issue by fabioCollini** [assertj/assertj#789]
I am writing a test to verify contents of a List<List<MyObject>>, something like this:

```java
List<List<String>> lists = Collections.singletonList(Arrays.asList("abc", "defg"));
```

I'd like to verify the contents of the internal list:

```java
assertThat(lists)
    .hasSize(1)
    .first()
    .extracting(String::length)
    .isEqualTo(3);
```

I think that I need to use an assertThat method with an additional parameter to specify the list element ([this](http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/Assertions.html#assertThat(java.util.List,%20org.assertj.core.api.AssertFactory)) method or [this](http://joel-costigliola.github.io/assertj/core/api/org/assertj/core/api/Assertions.html#assertThat(java.util.List,%20java.lang.Class)) one). I can't find the way to specify the type of the internal list, is there a simple way to write this kind of assertions?
I am using version 2.5 on an Android project.

**Comment by joel-costigliola** [comment]
hmmm, I'm indeed having an error when trying to use an assert factory, I suspect `assertThat(Iterable<? extends ELEMENT> actual,  AssertFactory<ELEMENT, ELEMENT_ASSERT> assertFactory)` to get in the way - I need to investigate more.

There is no easy way to check that except by using [condition](http://joel-costigliola.github.io/assertj/assertj-core-conditions.html) specially applying it on [elements](http://joel-costigliola.github.io/assertj/assertj-core-conditions.html#example-condition-on-collection). 

Another option is to flatten your list of list, probably the simpler solution.

**Comment by scordio** [comment]
Thanks, @Michael1993, we missed this one!

Your solution can also be shortened with [`singleElement(InstanceOfAssertFactory)`](https://www.javadoc.io/doc/org.assertj/assertj-core/latest/org/assertj/core/api/AbstractIterableAssert.html#singleElement(org.assertj.core.api.InstanceOfAssertFactory)):

```java
assertThat(lists)
  .singleElement(InstanceOfAssertFactories.list(String.class))
  .extracting(String::length)
  .isEqualTo(3);
```

@fabioCollini given the solution with the latest version, I am going to close this issue.
