### ISSUE TITLE
New assertion comparing XML strings

### ISSUE THREAD

**Issue by joel-costigliola** [assertj/assertj#96]
Let's integrate https://github.com/denlab/fest-assert-goodies work that had been done for Fest.

One thing though is not to add any dependency in assertj-core to avoid imposing unwanted dependency to assertj users (i.e. : no XOM).

The idea is to format both XML string the same way to be able to compare thme

**Comment by joel-costigliola** [comment]
I agree with that, I actually think that AssertJ should not compete with XMLUnit, properly doing XML assertions is a full time project.

**Comment by PascalSchumacher** [comment]
For reference there is an open pull request to add AssertJ support to XMLUnit 2: https://github.com/xmlunit/xmlunit/pull/120

**Comment by bodewig** [comment]
we've just released XMLUnit 2.6.1 with the new xmlunit-assertj module, see https://github.com/xmlunit/user-guide/wiki/CompareAssert
